import type { ListarCatalogosParams, ListarConFiltroParams } from "./types"

export const catalogosKeys = {
  all: ["catalogos"] as const,
  unidadesEjecutoras: () => [...catalogosKeys.all, "unidades-ejecutoras"] as const,
  unidadesEjecutorasList: (p?: ListarCatalogosParams) => [...catalogosKeys.unidadesEjecutoras(), "list", p] as const,
  unidadEjecutoraDetail: (id: number) => [...catalogosKeys.unidadesEjecutoras(), "detail", id] as const,
  tiposProyecto: () => [...catalogosKeys.all, "tipos-proyecto"] as const,
  tiposProyectoList: () => [...catalogosKeys.tiposProyecto(), "list"] as const,
  rubrosIngreso: () => [...catalogosKeys.all, "rubros-ingreso"] as const,
  rubrosIngresoList: (p?: ListarCatalogosParams) => [...catalogosKeys.rubrosIngreso(), "list", p] as const,
  rubroIngresoDetail: (id: number) => [...catalogosKeys.rubrosIngreso(), "detail", id] as const,
  rubrosGasto: () => [...catalogosKeys.all, "rubros-gasto"] as const,
  rubrosGastoList: (p?: ListarCatalogosParams) => [...catalogosKeys.rubrosGasto(), "list", p] as const,
  rubroGastoDetail: (id: number) => [...catalogosKeys.rubrosGasto(), "detail", id] as const,
  programasAcademicos: () => [...catalogosKeys.all, "programas-academicos"] as const,
  programasAcademicosList: (p?: ListarCatalogosParams) => [...catalogosKeys.programasAcademicos(), "list", p] as const,
  programaAcademicoDetail: (id: number) => [...catalogosKeys.programasAcademicos(), "detail", id] as const,
  periodosAcademicos: () => [...catalogosKeys.all, "periodos-academicos"] as const,
  periodosAcademicosList: (p?: ListarConFiltroParams) => [...catalogosKeys.periodosAcademicos(), "list", p] as const,
  periodoAcademicoDetail: (id: number) => [...catalogosKeys.periodosAcademicos(), "detail", id] as const,
  municipios: () => [...catalogosKeys.all, "municipios"] as const,
  municipiosList: (p?: ListarCatalogosParams) => [...catalogosKeys.municipios(), "list", p] as const,
  fuentesRecursos: () => [...catalogosKeys.all, "fuentes-recursos"] as const,
  fuentesRecursosList: (p?: ListarCatalogosParams) => [...catalogosKeys.fuentesRecursos(), "list", p] as const,
  fuenteRecursoDetail: (id: number) => [...catalogosKeys.fuentesRecursos(), "detail", id] as const,
  fechasLimite: () => [...catalogosKeys.all, "fechas-limite"] as const,
  fechasLimiteList: (p?: ListarConFiltroParams) => [...catalogosKeys.fechasLimite(), "list", p] as const,
  fechaLimiteDetail: (id: number) => [...catalogosKeys.fechasLimite(), "detail", id] as const,
  descuentos: () => [...catalogosKeys.all, "descuentos"] as const,
  descuentosList: (p?: ListarCatalogosParams) => [...catalogosKeys.descuentos(), "list", p] as const,
  descuentoDetail: (id: number) => [...catalogosKeys.descuentos(), "detail", id] as const,
  conceptosNomina: () => [...catalogosKeys.all, "conceptos-nomina"] as const,
  conceptosNominaList: (p?: ListarCatalogosParams) => [...catalogosKeys.conceptosNomina(), "list", p] as const,
  conceptoNominaDetail: (id: number) => [...catalogosKeys.conceptosNomina(), "detail", id] as const,
  apoyosMatricula: () => [...catalogosKeys.all, "apoyos-matricula"] as const,
  apoyosMatriculaList: (p?: ListarCatalogosParams) => [...catalogosKeys.apoyosMatricula(), "list", p] as const,
  apoyoMatriculaDetail: (id: number) => [...catalogosKeys.apoyosMatricula(), "detail", id] as const,
}
