/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './app/router/routes/__root'
import { Route as AuthenticatedRouteImport } from './app/router/routes/_authenticated'
import { Route as AuthRouteImport } from './app/router/routes/_auth'
import { Route as IndexRouteImport } from './app/router/routes/index'
import { Route as AuthenticatedSarViaticosRouteImport } from './app/router/routes/_authenticated/sar-viaticos'
import { Route as AuthenticatedPresupuestoRouteImport } from './app/router/routes/_authenticated/presupuesto'
import { Route as AuthenticatedPerfilRouteImport } from './app/router/routes/_authenticated/perfil'
import { Route as AuthenticatedNormatividadRouteImport } from './app/router/routes/_authenticated/normatividad'
import { Route as AuthenticatedNominaRouteImport } from './app/router/routes/_authenticated/nomina'
import { Route as AuthenticatedIntegracionRouteImport } from './app/router/routes/_authenticated/integracion'
import { Route as AuthenticatedEjecucionRouteImport } from './app/router/routes/_authenticated/ejecucion'
import { Route as AuthenticatedCatalogosRouteImport } from './app/router/routes/_authenticated/catalogos'
import { Route as AuthenticatedBalanceRouteImport } from './app/router/routes/_authenticated/balance'
import { Route as AuthenticatedAgendaRouteImport } from './app/router/routes/_authenticated/agenda'
import { Route as AuthLoginRouteImport } from './app/router/routes/_auth/login'
import { Route as AuthenticatedSarViaticosIndexRouteImport } from './app/router/routes/_authenticated/sar-viaticos/index'
import { Route as AuthenticatedProyectosIndexRouteImport } from './app/router/routes/_authenticated/proyectos/index'
import { Route as AuthenticatedPresupuestoIndexRouteImport } from './app/router/routes/_authenticated/presupuesto/index'
import { Route as AuthenticatedNormatividadIndexRouteImport } from './app/router/routes/_authenticated/normatividad/index'
import { Route as AuthenticatedNominaIndexRouteImport } from './app/router/routes/_authenticated/nomina/index'
import { Route as AuthenticatedModificacionesIndexRouteImport } from './app/router/routes/_authenticated/modificaciones/index'
import { Route as AuthenticatedMatriculasIndexRouteImport } from './app/router/routes/_authenticated/matriculas/index'
import { Route as AuthenticatedIntegracionIndexRouteImport } from './app/router/routes/_authenticated/integracion/index'
import { Route as AuthenticatedEjecucionIndexRouteImport } from './app/router/routes/_authenticated/ejecucion/index'
import { Route as AuthenticatedDocumentosIndexRouteImport } from './app/router/routes/_authenticated/documentos/index'
import { Route as AuthenticatedDashboardIndexRouteImport } from './app/router/routes/_authenticated/dashboard/index'
import { Route as AuthenticatedCatalogosIndexRouteImport } from './app/router/routes/_authenticated/catalogos/index'
import { Route as AuthenticatedBalanceIndexRouteImport } from './app/router/routes/_authenticated/balance/index'
import { Route as AuthenticatedAgendaIndexRouteImport } from './app/router/routes/_authenticated/agenda/index'
import { Route as AuthenticatedAdminIndexRouteImport } from './app/router/routes/_authenticated/admin/index'
import { Route as AuthenticatedSarViaticosViaticosRouteImport } from './app/router/routes/_authenticated/sar-viaticos/viaticos'
import { Route as AuthenticatedSarViaticosTarifasRouteImport } from './app/router/routes/_authenticated/sar-viaticos/tarifas'
import { Route as AuthenticatedSarViaticosSarRouteImport } from './app/router/routes/_authenticated/sar-viaticos/sar'
import { Route as AuthenticatedProyectosIdRouteImport } from './app/router/routes/_authenticated/proyectos/$id'
import { Route as AuthenticatedPerfil2faRouteImport } from './app/router/routes/_authenticated/perfil/2fa'
import { Route as AuthenticatedNormatividadNormasRouteImport } from './app/router/routes/_authenticated/normatividad/normas'
import { Route as AuthenticatedNominaPuntosSalarialesRouteImport } from './app/router/routes/_authenticated/nomina/puntos-salariales'
import { Route as AuthenticatedNominaPlanClasesRouteImport } from './app/router/routes/_authenticated/nomina/plan-clases'
import { Route as AuthenticatedNominaLiquidacionRouteImport } from './app/router/routes/_authenticated/nomina/liquidacion'
import { Route as AuthenticatedNominaEmpleadosRouteImport } from './app/router/routes/_authenticated/nomina/empleados'
import { Route as AuthenticatedNominaCostosParafiscalesRouteImport } from './app/router/routes/_authenticated/nomina/costos-parafiscales'
import { Route as AuthenticatedNominaConciliacionRouteImport } from './app/router/routes/_authenticated/nomina/conciliacion'
import { Route as AuthenticatedModificacionesIdRouteImport } from './app/router/routes/_authenticated/modificaciones/$id'
import { Route as AuthenticatedMatriculasTransferenciasRouteImport } from './app/router/routes/_authenticated/matriculas/transferencias'
import { Route as AuthenticatedMatriculasResumenRouteImport } from './app/router/routes/_authenticated/matriculas/resumen'
import { Route as AuthenticatedMatriculasCohortesRouteImport } from './app/router/routes/_authenticated/matriculas/cohortes'
import { Route as AuthenticatedMatriculasCoberturaPicRouteImport } from './app/router/routes/_authenticated/matriculas/cobertura-pic'
import { Route as AuthenticatedMatriculasBecasPosgradoRouteImport } from './app/router/routes/_authenticated/matriculas/becas-posgrado'
import { Route as AuthenticatedEjecucionRpRouteImport } from './app/router/routes/_authenticated/ejecucion/rp'
import { Route as AuthenticatedEjecucionReservasRouteImport } from './app/router/routes/_authenticated/ejecucion/reservas'
import { Route as AuthenticatedEjecucionReportesRouteImport } from './app/router/routes/_authenticated/ejecucion/reportes'
import { Route as AuthenticatedEjecucionRadicacionRouteImport } from './app/router/routes/_authenticated/ejecucion/radicacion'
import { Route as AuthenticatedEjecucionOpRouteImport } from './app/router/routes/_authenticated/ejecucion/op'
import { Route as AuthenticatedEjecucionCdpRouteImport } from './app/router/routes/_authenticated/ejecucion/cdp'
import { Route as AuthenticatedEjecucionAvancesRouteImport } from './app/router/routes/_authenticated/ejecucion/avances'
import { Route as AuthenticatedDocumentosIdRouteImport } from './app/router/routes/_authenticated/documentos/$id'
import { Route as AuthenticatedDashboardSeguimientoRouteImport } from './app/router/routes/_authenticated/dashboard/seguimiento'
import { Route as AuthenticatedDashboardInformesRouteImport } from './app/router/routes/_authenticated/dashboard/informes'
import { Route as AuthenticatedCatalogosUnidadesEjecutorasRouteImport } from './app/router/routes/_authenticated/catalogos/unidades-ejecutoras'
import { Route as AuthenticatedCatalogosTiposProyectoRouteImport } from './app/router/routes/_authenticated/catalogos/tipos-proyecto'
import { Route as AuthenticatedCatalogosRubrosIngresoRouteImport } from './app/router/routes/_authenticated/catalogos/rubros-ingreso'
import { Route as AuthenticatedCatalogosRubrosGastoRouteImport } from './app/router/routes/_authenticated/catalogos/rubros-gasto'
import { Route as AuthenticatedCatalogosProgramasAcademicosRouteImport } from './app/router/routes/_authenticated/catalogos/programas-academicos'
import { Route as AuthenticatedCatalogosPeriodosAcademicosRouteImport } from './app/router/routes/_authenticated/catalogos/periodos-academicos'
import { Route as AuthenticatedCatalogosMunicipiosRouteImport } from './app/router/routes/_authenticated/catalogos/municipios'
import { Route as AuthenticatedCatalogosFuentesRecursosRouteImport } from './app/router/routes/_authenticated/catalogos/fuentes-recursos'
import { Route as AuthenticatedCatalogosFechasLimiteRouteImport } from './app/router/routes/_authenticated/catalogos/fechas-limite'
import { Route as AuthenticatedCatalogosDescuentosRouteImport } from './app/router/routes/_authenticated/catalogos/descuentos'
import { Route as AuthenticatedCatalogosConceptosNominaRouteImport } from './app/router/routes/_authenticated/catalogos/conceptos-nomina'
import { Route as AuthenticatedCatalogosApoyosMatriculaRouteImport } from './app/router/routes/_authenticated/catalogos/apoyos-matricula'
import { Route as AuthenticatedBalanceRecursosRouteImport } from './app/router/routes/_authenticated/balance/recursos'
import { Route as AuthenticatedBalanceRecaudosRouteImport } from './app/router/routes/_authenticated/balance/recaudos'
import { Route as AuthenticatedBalanceFlujoCajaRouteImport } from './app/router/routes/_authenticated/balance/flujo-caja'
import { Route as AuthenticatedBalanceConciliacionRouteImport } from './app/router/routes/_authenticated/balance/conciliacion'
import { Route as AuthenticatedBalanceCierreRouteImport } from './app/router/routes/_authenticated/balance/cierre'
import { Route as AuthenticatedAgendaMiAgendaRouteImport } from './app/router/routes/_authenticated/agenda/mi-agenda'
import { Route as AuthenticatedAgendaEventosRouteImport } from './app/router/routes/_authenticated/agenda/eventos'
import { Route as AuthenticatedAdminVigenciasRouteImport } from './app/router/routes/_authenticated/admin/vigencias'
import { Route as AuthenticatedPresupuestoIngresosIndexRouteImport } from './app/router/routes/_authenticated/presupuesto/ingresos/index'
import { Route as AuthenticatedPresupuestoGastosIndexRouteImport } from './app/router/routes/_authenticated/presupuesto/gastos/index'
import { Route as AuthenticatedPresupuestoEtapasIndexRouteImport } from './app/router/routes/_authenticated/presupuesto/etapas/index'
import { Route as AuthenticatedPresupuestoEjecucionMensualIndexRouteImport } from './app/router/routes/_authenticated/presupuesto/ejecucion-mensual/index'
import { Route as AuthenticatedAdminUsuariosIndexRouteImport } from './app/router/routes/_authenticated/admin/usuarios/index'
import { Route as AuthenticatedAdminRolesIndexRouteImport } from './app/router/routes/_authenticated/admin/roles/index'
import { Route as AuthenticatedAdminAuditoriaIndexRouteImport } from './app/router/routes/_authenticated/admin/auditoria/index'
import { Route as AuthenticatedSarViaticosViaticosIdRouteImport } from './app/router/routes/_authenticated/sar-viaticos/viaticos.$id'
import { Route as AuthenticatedSarViaticosSarIdRouteImport } from './app/router/routes/_authenticated/sar-viaticos/sar.$id'
import { Route as AuthenticatedAdminUsuariosIdRouteImport } from './app/router/routes/_authenticated/admin/usuarios/$id'
import { Route as AuthenticatedAdminRolesIdRouteImport } from './app/router/routes/_authenticated/admin/roles/$id'

const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSarViaticosRoute =
  AuthenticatedSarViaticosRouteImport.update({
    id: '/sar-viaticos',
    path: '/sar-viaticos',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPresupuestoRoute =
  AuthenticatedPresupuestoRouteImport.update({
    id: '/presupuesto',
    path: '/presupuesto',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPerfilRoute = AuthenticatedPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedNormatividadRoute =
  AuthenticatedNormatividadRouteImport.update({
    id: '/normatividad',
    path: '/normatividad',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedNominaRoute = AuthenticatedNominaRouteImport.update({
  id: '/nomina',
  path: '/nomina',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedIntegracionRoute =
  AuthenticatedIntegracionRouteImport.update({
    id: '/integracion',
    path: '/integracion',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedEjecucionRoute = AuthenticatedEjecucionRouteImport.update({
  id: '/ejecucion',
  path: '/ejecucion',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCatalogosRoute = AuthenticatedCatalogosRouteImport.update({
  id: '/catalogos',
  path: '/catalogos',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedBalanceRoute = AuthenticatedBalanceRouteImport.update({
  id: '/balance',
  path: '/balance',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAgendaRoute = AuthenticatedAgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const AuthenticatedSarViaticosIndexRoute =
  AuthenticatedSarViaticosIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedSarViaticosRoute,
  } as any)
const AuthenticatedProyectosIndexRoute =
  AuthenticatedProyectosIndexRouteImport.update({
    id: '/proyectos/',
    path: '/proyectos/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPresupuestoIndexRoute =
  AuthenticatedPresupuestoIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedPresupuestoRoute,
  } as any)
const AuthenticatedNormatividadIndexRoute =
  AuthenticatedNormatividadIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedNormatividadRoute,
  } as any)
const AuthenticatedNominaIndexRoute =
  AuthenticatedNominaIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedNominaRoute,
  } as any)
const AuthenticatedModificacionesIndexRoute =
  AuthenticatedModificacionesIndexRouteImport.update({
    id: '/modificaciones/',
    path: '/modificaciones/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMatriculasIndexRoute =
  AuthenticatedMatriculasIndexRouteImport.update({
    id: '/matriculas/',
    path: '/matriculas/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedIntegracionIndexRoute =
  AuthenticatedIntegracionIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedIntegracionRoute,
  } as any)
const AuthenticatedEjecucionIndexRoute =
  AuthenticatedEjecucionIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedEjecucionRoute,
  } as any)
const AuthenticatedDocumentosIndexRoute =
  AuthenticatedDocumentosIndexRouteImport.update({
    id: '/documentos/',
    path: '/documentos/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDashboardIndexRoute =
  AuthenticatedDashboardIndexRouteImport.update({
    id: '/dashboard/',
    path: '/dashboard/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCatalogosIndexRoute =
  AuthenticatedCatalogosIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedCatalogosRoute,
  } as any)
const AuthenticatedBalanceIndexRoute =
  AuthenticatedBalanceIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedBalanceRoute,
  } as any)
const AuthenticatedAgendaIndexRoute =
  AuthenticatedAgendaIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAgendaRoute,
  } as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSarViaticosViaticosRoute =
  AuthenticatedSarViaticosViaticosRouteImport.update({
    id: '/viaticos',
    path: '/viaticos',
    getParentRoute: () => AuthenticatedSarViaticosRoute,
  } as any)
const AuthenticatedSarViaticosTarifasRoute =
  AuthenticatedSarViaticosTarifasRouteImport.update({
    id: '/tarifas',
    path: '/tarifas',
    getParentRoute: () => AuthenticatedSarViaticosRoute,
  } as any)
const AuthenticatedSarViaticosSarRoute =
  AuthenticatedSarViaticosSarRouteImport.update({
    id: '/sar',
    path: '/sar',
    getParentRoute: () => AuthenticatedSarViaticosRoute,
  } as any)
const AuthenticatedProyectosIdRoute =
  AuthenticatedProyectosIdRouteImport.update({
    id: '/proyectos/$id',
    path: '/proyectos/$id',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPerfil2faRoute = AuthenticatedPerfil2faRouteImport.update({
  id: '/2fa',
  path: '/2fa',
  getParentRoute: () => AuthenticatedPerfilRoute,
} as any)
const AuthenticatedNormatividadNormasRoute =
  AuthenticatedNormatividadNormasRouteImport.update({
    id: '/normas',
    path: '/normas',
    getParentRoute: () => AuthenticatedNormatividadRoute,
  } as any)
const AuthenticatedNominaPuntosSalarialesRoute =
  AuthenticatedNominaPuntosSalarialesRouteImport.update({
    id: '/puntos-salariales',
    path: '/puntos-salariales',
    getParentRoute: () => AuthenticatedNominaRoute,
  } as any)
const AuthenticatedNominaPlanClasesRoute =
  AuthenticatedNominaPlanClasesRouteImport.update({
    id: '/plan-clases',
    path: '/plan-clases',
    getParentRoute: () => AuthenticatedNominaRoute,
  } as any)
const AuthenticatedNominaLiquidacionRoute =
  AuthenticatedNominaLiquidacionRouteImport.update({
    id: '/liquidacion',
    path: '/liquidacion',
    getParentRoute: () => AuthenticatedNominaRoute,
  } as any)
const AuthenticatedNominaEmpleadosRoute =
  AuthenticatedNominaEmpleadosRouteImport.update({
    id: '/empleados',
    path: '/empleados',
    getParentRoute: () => AuthenticatedNominaRoute,
  } as any)
const AuthenticatedNominaCostosParafiscalesRoute =
  AuthenticatedNominaCostosParafiscalesRouteImport.update({
    id: '/costos-parafiscales',
    path: '/costos-parafiscales',
    getParentRoute: () => AuthenticatedNominaRoute,
  } as any)
const AuthenticatedNominaConciliacionRoute =
  AuthenticatedNominaConciliacionRouteImport.update({
    id: '/conciliacion',
    path: '/conciliacion',
    getParentRoute: () => AuthenticatedNominaRoute,
  } as any)
const AuthenticatedModificacionesIdRoute =
  AuthenticatedModificacionesIdRouteImport.update({
    id: '/modificaciones/$id',
    path: '/modificaciones/$id',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMatriculasTransferenciasRoute =
  AuthenticatedMatriculasTransferenciasRouteImport.update({
    id: '/matriculas/transferencias',
    path: '/matriculas/transferencias',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMatriculasResumenRoute =
  AuthenticatedMatriculasResumenRouteImport.update({
    id: '/matriculas/resumen',
    path: '/matriculas/resumen',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMatriculasCohortesRoute =
  AuthenticatedMatriculasCohortesRouteImport.update({
    id: '/matriculas/cohortes',
    path: '/matriculas/cohortes',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMatriculasCoberturaPicRoute =
  AuthenticatedMatriculasCoberturaPicRouteImport.update({
    id: '/matriculas/cobertura-pic',
    path: '/matriculas/cobertura-pic',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMatriculasBecasPosgradoRoute =
  AuthenticatedMatriculasBecasPosgradoRouteImport.update({
    id: '/matriculas/becas-posgrado',
    path: '/matriculas/becas-posgrado',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedEjecucionRpRoute =
  AuthenticatedEjecucionRpRouteImport.update({
    id: '/rp',
    path: '/rp',
    getParentRoute: () => AuthenticatedEjecucionRoute,
  } as any)
const AuthenticatedEjecucionReservasRoute =
  AuthenticatedEjecucionReservasRouteImport.update({
    id: '/reservas',
    path: '/reservas',
    getParentRoute: () => AuthenticatedEjecucionRoute,
  } as any)
const AuthenticatedEjecucionReportesRoute =
  AuthenticatedEjecucionReportesRouteImport.update({
    id: '/reportes',
    path: '/reportes',
    getParentRoute: () => AuthenticatedEjecucionRoute,
  } as any)
const AuthenticatedEjecucionRadicacionRoute =
  AuthenticatedEjecucionRadicacionRouteImport.update({
    id: '/radicacion',
    path: '/radicacion',
    getParentRoute: () => AuthenticatedEjecucionRoute,
  } as any)
const AuthenticatedEjecucionOpRoute =
  AuthenticatedEjecucionOpRouteImport.update({
    id: '/op',
    path: '/op',
    getParentRoute: () => AuthenticatedEjecucionRoute,
  } as any)
const AuthenticatedEjecucionCdpRoute =
  AuthenticatedEjecucionCdpRouteImport.update({
    id: '/cdp',
    path: '/cdp',
    getParentRoute: () => AuthenticatedEjecucionRoute,
  } as any)
const AuthenticatedEjecucionAvancesRoute =
  AuthenticatedEjecucionAvancesRouteImport.update({
    id: '/avances',
    path: '/avances',
    getParentRoute: () => AuthenticatedEjecucionRoute,
  } as any)
const AuthenticatedDocumentosIdRoute =
  AuthenticatedDocumentosIdRouteImport.update({
    id: '/documentos/$id',
    path: '/documentos/$id',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDashboardSeguimientoRoute =
  AuthenticatedDashboardSeguimientoRouteImport.update({
    id: '/dashboard/seguimiento',
    path: '/dashboard/seguimiento',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDashboardInformesRoute =
  AuthenticatedDashboardInformesRouteImport.update({
    id: '/dashboard/informes',
    path: '/dashboard/informes',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCatalogosUnidadesEjecutorasRoute =
  AuthenticatedCatalogosUnidadesEjecutorasRouteImport.update({
    id: '/unidades-ejecutoras',
    path: '/unidades-ejecutoras',
    getParentRoute: () => AuthenticatedCatalogosRoute,
  } as any)
const AuthenticatedCatalogosTiposProyectoRoute =
  AuthenticatedCatalogosTiposProyectoRouteImport.update({
    id: '/tipos-proyecto',
    path: '/tipos-proyecto',
    getParentRoute: () => AuthenticatedCatalogosRoute,
  } as any)
const AuthenticatedCatalogosRubrosIngresoRoute =
  AuthenticatedCatalogosRubrosIngresoRouteImport.update({
    id: '/rubros-ingreso',
    path: '/rubros-ingreso',
    getParentRoute: () => AuthenticatedCatalogosRoute,
  } as any)
const AuthenticatedCatalogosRubrosGastoRoute =
  AuthenticatedCatalogosRubrosGastoRouteImport.update({
    id: '/rubros-gasto',
    path: '/rubros-gasto',
    getParentRoute: () => AuthenticatedCatalogosRoute,
  } as any)
const AuthenticatedCatalogosProgramasAcademicosRoute =
  AuthenticatedCatalogosProgramasAcademicosRouteImport.update({
    id: '/programas-academicos',
    path: '/programas-academicos',
    getParentRoute: () => AuthenticatedCatalogosRoute,
  } as any)
const AuthenticatedCatalogosPeriodosAcademicosRoute =
  AuthenticatedCatalogosPeriodosAcademicosRouteImport.update({
    id: '/periodos-academicos',
    path: '/periodos-academicos',
    getParentRoute: () => AuthenticatedCatalogosRoute,
  } as any)
const AuthenticatedCatalogosMunicipiosRoute =
  AuthenticatedCatalogosMunicipiosRouteImport.update({
    id: '/municipios',
    path: '/municipios',
    getParentRoute: () => AuthenticatedCatalogosRoute,
  } as any)
const AuthenticatedCatalogosFuentesRecursosRoute =
  AuthenticatedCatalogosFuentesRecursosRouteImport.update({
    id: '/fuentes-recursos',
    path: '/fuentes-recursos',
    getParentRoute: () => AuthenticatedCatalogosRoute,
  } as any)
const AuthenticatedCatalogosFechasLimiteRoute =
  AuthenticatedCatalogosFechasLimiteRouteImport.update({
    id: '/fechas-limite',
    path: '/fechas-limite',
    getParentRoute: () => AuthenticatedCatalogosRoute,
  } as any)
const AuthenticatedCatalogosDescuentosRoute =
  AuthenticatedCatalogosDescuentosRouteImport.update({
    id: '/descuentos',
    path: '/descuentos',
    getParentRoute: () => AuthenticatedCatalogosRoute,
  } as any)
const AuthenticatedCatalogosConceptosNominaRoute =
  AuthenticatedCatalogosConceptosNominaRouteImport.update({
    id: '/conceptos-nomina',
    path: '/conceptos-nomina',
    getParentRoute: () => AuthenticatedCatalogosRoute,
  } as any)
const AuthenticatedCatalogosApoyosMatriculaRoute =
  AuthenticatedCatalogosApoyosMatriculaRouteImport.update({
    id: '/apoyos-matricula',
    path: '/apoyos-matricula',
    getParentRoute: () => AuthenticatedCatalogosRoute,
  } as any)
const AuthenticatedBalanceRecursosRoute =
  AuthenticatedBalanceRecursosRouteImport.update({
    id: '/recursos',
    path: '/recursos',
    getParentRoute: () => AuthenticatedBalanceRoute,
  } as any)
const AuthenticatedBalanceRecaudosRoute =
  AuthenticatedBalanceRecaudosRouteImport.update({
    id: '/recaudos',
    path: '/recaudos',
    getParentRoute: () => AuthenticatedBalanceRoute,
  } as any)
const AuthenticatedBalanceFlujoCajaRoute =
  AuthenticatedBalanceFlujoCajaRouteImport.update({
    id: '/flujo-caja',
    path: '/flujo-caja',
    getParentRoute: () => AuthenticatedBalanceRoute,
  } as any)
const AuthenticatedBalanceConciliacionRoute =
  AuthenticatedBalanceConciliacionRouteImport.update({
    id: '/conciliacion',
    path: '/conciliacion',
    getParentRoute: () => AuthenticatedBalanceRoute,
  } as any)
const AuthenticatedBalanceCierreRoute =
  AuthenticatedBalanceCierreRouteImport.update({
    id: '/cierre',
    path: '/cierre',
    getParentRoute: () => AuthenticatedBalanceRoute,
  } as any)
const AuthenticatedAgendaMiAgendaRoute =
  AuthenticatedAgendaMiAgendaRouteImport.update({
    id: '/mi-agenda',
    path: '/mi-agenda',
    getParentRoute: () => AuthenticatedAgendaRoute,
  } as any)
const AuthenticatedAgendaEventosRoute =
  AuthenticatedAgendaEventosRouteImport.update({
    id: '/eventos',
    path: '/eventos',
    getParentRoute: () => AuthenticatedAgendaRoute,
  } as any)
const AuthenticatedAdminVigenciasRoute =
  AuthenticatedAdminVigenciasRouteImport.update({
    id: '/admin/vigencias',
    path: '/admin/vigencias',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPresupuestoIngresosIndexRoute =
  AuthenticatedPresupuestoIngresosIndexRouteImport.update({
    id: '/ingresos/',
    path: '/ingresos/',
    getParentRoute: () => AuthenticatedPresupuestoRoute,
  } as any)
const AuthenticatedPresupuestoGastosIndexRoute =
  AuthenticatedPresupuestoGastosIndexRouteImport.update({
    id: '/gastos/',
    path: '/gastos/',
    getParentRoute: () => AuthenticatedPresupuestoRoute,
  } as any)
const AuthenticatedPresupuestoEtapasIndexRoute =
  AuthenticatedPresupuestoEtapasIndexRouteImport.update({
    id: '/etapas/',
    path: '/etapas/',
    getParentRoute: () => AuthenticatedPresupuestoRoute,
  } as any)
const AuthenticatedPresupuestoEjecucionMensualIndexRoute =
  AuthenticatedPresupuestoEjecucionMensualIndexRouteImport.update({
    id: '/ejecucion-mensual/',
    path: '/ejecucion-mensual/',
    getParentRoute: () => AuthenticatedPresupuestoRoute,
  } as any)
const AuthenticatedAdminUsuariosIndexRoute =
  AuthenticatedAdminUsuariosIndexRouteImport.update({
    id: '/admin/usuarios/',
    path: '/admin/usuarios/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminRolesIndexRoute =
  AuthenticatedAdminRolesIndexRouteImport.update({
    id: '/admin/roles/',
    path: '/admin/roles/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminAuditoriaIndexRoute =
  AuthenticatedAdminAuditoriaIndexRouteImport.update({
    id: '/admin/auditoria/',
    path: '/admin/auditoria/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSarViaticosViaticosIdRoute =
  AuthenticatedSarViaticosViaticosIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedSarViaticosViaticosRoute,
  } as any)
const AuthenticatedSarViaticosSarIdRoute =
  AuthenticatedSarViaticosSarIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedSarViaticosSarRoute,
  } as any)
const AuthenticatedAdminUsuariosIdRoute =
  AuthenticatedAdminUsuariosIdRouteImport.update({
    id: '/admin/usuarios/$id',
    path: '/admin/usuarios/$id',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminRolesIdRoute =
  AuthenticatedAdminRolesIdRouteImport.update({
    id: '/admin/roles/$id',
    path: '/admin/roles/$id',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof AuthLoginRoute
  '/agenda': typeof AuthenticatedAgendaRouteWithChildren
  '/balance': typeof AuthenticatedBalanceRouteWithChildren
  '/catalogos': typeof AuthenticatedCatalogosRouteWithChildren
  '/ejecucion': typeof AuthenticatedEjecucionRouteWithChildren
  '/integracion': typeof AuthenticatedIntegracionRouteWithChildren
  '/nomina': typeof AuthenticatedNominaRouteWithChildren
  '/normatividad': typeof AuthenticatedNormatividadRouteWithChildren
  '/perfil': typeof AuthenticatedPerfilRouteWithChildren
  '/presupuesto': typeof AuthenticatedPresupuestoRouteWithChildren
  '/sar-viaticos': typeof AuthenticatedSarViaticosRouteWithChildren
  '/admin/vigencias': typeof AuthenticatedAdminVigenciasRoute
  '/agenda/eventos': typeof AuthenticatedAgendaEventosRoute
  '/agenda/mi-agenda': typeof AuthenticatedAgendaMiAgendaRoute
  '/balance/cierre': typeof AuthenticatedBalanceCierreRoute
  '/balance/conciliacion': typeof AuthenticatedBalanceConciliacionRoute
  '/balance/flujo-caja': typeof AuthenticatedBalanceFlujoCajaRoute
  '/balance/recaudos': typeof AuthenticatedBalanceRecaudosRoute
  '/balance/recursos': typeof AuthenticatedBalanceRecursosRoute
  '/catalogos/apoyos-matricula': typeof AuthenticatedCatalogosApoyosMatriculaRoute
  '/catalogos/conceptos-nomina': typeof AuthenticatedCatalogosConceptosNominaRoute
  '/catalogos/descuentos': typeof AuthenticatedCatalogosDescuentosRoute
  '/catalogos/fechas-limite': typeof AuthenticatedCatalogosFechasLimiteRoute
  '/catalogos/fuentes-recursos': typeof AuthenticatedCatalogosFuentesRecursosRoute
  '/catalogos/municipios': typeof AuthenticatedCatalogosMunicipiosRoute
  '/catalogos/periodos-academicos': typeof AuthenticatedCatalogosPeriodosAcademicosRoute
  '/catalogos/programas-academicos': typeof AuthenticatedCatalogosProgramasAcademicosRoute
  '/catalogos/rubros-gasto': typeof AuthenticatedCatalogosRubrosGastoRoute
  '/catalogos/rubros-ingreso': typeof AuthenticatedCatalogosRubrosIngresoRoute
  '/catalogos/tipos-proyecto': typeof AuthenticatedCatalogosTiposProyectoRoute
  '/catalogos/unidades-ejecutoras': typeof AuthenticatedCatalogosUnidadesEjecutorasRoute
  '/dashboard/informes': typeof AuthenticatedDashboardInformesRoute
  '/dashboard/seguimiento': typeof AuthenticatedDashboardSeguimientoRoute
  '/documentos/$id': typeof AuthenticatedDocumentosIdRoute
  '/ejecucion/avances': typeof AuthenticatedEjecucionAvancesRoute
  '/ejecucion/cdp': typeof AuthenticatedEjecucionCdpRoute
  '/ejecucion/op': typeof AuthenticatedEjecucionOpRoute
  '/ejecucion/radicacion': typeof AuthenticatedEjecucionRadicacionRoute
  '/ejecucion/reportes': typeof AuthenticatedEjecucionReportesRoute
  '/ejecucion/reservas': typeof AuthenticatedEjecucionReservasRoute
  '/ejecucion/rp': typeof AuthenticatedEjecucionRpRoute
  '/matriculas/becas-posgrado': typeof AuthenticatedMatriculasBecasPosgradoRoute
  '/matriculas/cobertura-pic': typeof AuthenticatedMatriculasCoberturaPicRoute
  '/matriculas/cohortes': typeof AuthenticatedMatriculasCohortesRoute
  '/matriculas/resumen': typeof AuthenticatedMatriculasResumenRoute
  '/matriculas/transferencias': typeof AuthenticatedMatriculasTransferenciasRoute
  '/modificaciones/$id': typeof AuthenticatedModificacionesIdRoute
  '/nomina/conciliacion': typeof AuthenticatedNominaConciliacionRoute
  '/nomina/costos-parafiscales': typeof AuthenticatedNominaCostosParafiscalesRoute
  '/nomina/empleados': typeof AuthenticatedNominaEmpleadosRoute
  '/nomina/liquidacion': typeof AuthenticatedNominaLiquidacionRoute
  '/nomina/plan-clases': typeof AuthenticatedNominaPlanClasesRoute
  '/nomina/puntos-salariales': typeof AuthenticatedNominaPuntosSalarialesRoute
  '/normatividad/normas': typeof AuthenticatedNormatividadNormasRoute
  '/perfil/2fa': typeof AuthenticatedPerfil2faRoute
  '/proyectos/$id': typeof AuthenticatedProyectosIdRoute
  '/sar-viaticos/sar': typeof AuthenticatedSarViaticosSarRouteWithChildren
  '/sar-viaticos/tarifas': typeof AuthenticatedSarViaticosTarifasRoute
  '/sar-viaticos/viaticos': typeof AuthenticatedSarViaticosViaticosRouteWithChildren
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/agenda/': typeof AuthenticatedAgendaIndexRoute
  '/balance/': typeof AuthenticatedBalanceIndexRoute
  '/catalogos/': typeof AuthenticatedCatalogosIndexRoute
  '/dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/documentos/': typeof AuthenticatedDocumentosIndexRoute
  '/ejecucion/': typeof AuthenticatedEjecucionIndexRoute
  '/integracion/': typeof AuthenticatedIntegracionIndexRoute
  '/matriculas/': typeof AuthenticatedMatriculasIndexRoute
  '/modificaciones/': typeof AuthenticatedModificacionesIndexRoute
  '/nomina/': typeof AuthenticatedNominaIndexRoute
  '/normatividad/': typeof AuthenticatedNormatividadIndexRoute
  '/presupuesto/': typeof AuthenticatedPresupuestoIndexRoute
  '/proyectos/': typeof AuthenticatedProyectosIndexRoute
  '/sar-viaticos/': typeof AuthenticatedSarViaticosIndexRoute
  '/admin/roles/$id': typeof AuthenticatedAdminRolesIdRoute
  '/admin/usuarios/$id': typeof AuthenticatedAdminUsuariosIdRoute
  '/sar-viaticos/sar/$id': typeof AuthenticatedSarViaticosSarIdRoute
  '/sar-viaticos/viaticos/$id': typeof AuthenticatedSarViaticosViaticosIdRoute
  '/admin/auditoria/': typeof AuthenticatedAdminAuditoriaIndexRoute
  '/admin/roles/': typeof AuthenticatedAdminRolesIndexRoute
  '/admin/usuarios/': typeof AuthenticatedAdminUsuariosIndexRoute
  '/presupuesto/ejecucion-mensual/': typeof AuthenticatedPresupuestoEjecucionMensualIndexRoute
  '/presupuesto/etapas/': typeof AuthenticatedPresupuestoEtapasIndexRoute
  '/presupuesto/gastos/': typeof AuthenticatedPresupuestoGastosIndexRoute
  '/presupuesto/ingresos/': typeof AuthenticatedPresupuestoIngresosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof AuthLoginRoute
  '/perfil': typeof AuthenticatedPerfilRouteWithChildren
  '/admin/vigencias': typeof AuthenticatedAdminVigenciasRoute
  '/agenda/eventos': typeof AuthenticatedAgendaEventosRoute
  '/agenda/mi-agenda': typeof AuthenticatedAgendaMiAgendaRoute
  '/balance/cierre': typeof AuthenticatedBalanceCierreRoute
  '/balance/conciliacion': typeof AuthenticatedBalanceConciliacionRoute
  '/balance/flujo-caja': typeof AuthenticatedBalanceFlujoCajaRoute
  '/balance/recaudos': typeof AuthenticatedBalanceRecaudosRoute
  '/balance/recursos': typeof AuthenticatedBalanceRecursosRoute
  '/catalogos/apoyos-matricula': typeof AuthenticatedCatalogosApoyosMatriculaRoute
  '/catalogos/conceptos-nomina': typeof AuthenticatedCatalogosConceptosNominaRoute
  '/catalogos/descuentos': typeof AuthenticatedCatalogosDescuentosRoute
  '/catalogos/fechas-limite': typeof AuthenticatedCatalogosFechasLimiteRoute
  '/catalogos/fuentes-recursos': typeof AuthenticatedCatalogosFuentesRecursosRoute
  '/catalogos/municipios': typeof AuthenticatedCatalogosMunicipiosRoute
  '/catalogos/periodos-academicos': typeof AuthenticatedCatalogosPeriodosAcademicosRoute
  '/catalogos/programas-academicos': typeof AuthenticatedCatalogosProgramasAcademicosRoute
  '/catalogos/rubros-gasto': typeof AuthenticatedCatalogosRubrosGastoRoute
  '/catalogos/rubros-ingreso': typeof AuthenticatedCatalogosRubrosIngresoRoute
  '/catalogos/tipos-proyecto': typeof AuthenticatedCatalogosTiposProyectoRoute
  '/catalogos/unidades-ejecutoras': typeof AuthenticatedCatalogosUnidadesEjecutorasRoute
  '/dashboard/informes': typeof AuthenticatedDashboardInformesRoute
  '/dashboard/seguimiento': typeof AuthenticatedDashboardSeguimientoRoute
  '/documentos/$id': typeof AuthenticatedDocumentosIdRoute
  '/ejecucion/avances': typeof AuthenticatedEjecucionAvancesRoute
  '/ejecucion/cdp': typeof AuthenticatedEjecucionCdpRoute
  '/ejecucion/op': typeof AuthenticatedEjecucionOpRoute
  '/ejecucion/radicacion': typeof AuthenticatedEjecucionRadicacionRoute
  '/ejecucion/reportes': typeof AuthenticatedEjecucionReportesRoute
  '/ejecucion/reservas': typeof AuthenticatedEjecucionReservasRoute
  '/ejecucion/rp': typeof AuthenticatedEjecucionRpRoute
  '/matriculas/becas-posgrado': typeof AuthenticatedMatriculasBecasPosgradoRoute
  '/matriculas/cobertura-pic': typeof AuthenticatedMatriculasCoberturaPicRoute
  '/matriculas/cohortes': typeof AuthenticatedMatriculasCohortesRoute
  '/matriculas/resumen': typeof AuthenticatedMatriculasResumenRoute
  '/matriculas/transferencias': typeof AuthenticatedMatriculasTransferenciasRoute
  '/modificaciones/$id': typeof AuthenticatedModificacionesIdRoute
  '/nomina/conciliacion': typeof AuthenticatedNominaConciliacionRoute
  '/nomina/costos-parafiscales': typeof AuthenticatedNominaCostosParafiscalesRoute
  '/nomina/empleados': typeof AuthenticatedNominaEmpleadosRoute
  '/nomina/liquidacion': typeof AuthenticatedNominaLiquidacionRoute
  '/nomina/plan-clases': typeof AuthenticatedNominaPlanClasesRoute
  '/nomina/puntos-salariales': typeof AuthenticatedNominaPuntosSalarialesRoute
  '/normatividad/normas': typeof AuthenticatedNormatividadNormasRoute
  '/perfil/2fa': typeof AuthenticatedPerfil2faRoute
  '/proyectos/$id': typeof AuthenticatedProyectosIdRoute
  '/sar-viaticos/sar': typeof AuthenticatedSarViaticosSarRouteWithChildren
  '/sar-viaticos/tarifas': typeof AuthenticatedSarViaticosTarifasRoute
  '/sar-viaticos/viaticos': typeof AuthenticatedSarViaticosViaticosRouteWithChildren
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/agenda': typeof AuthenticatedAgendaIndexRoute
  '/balance': typeof AuthenticatedBalanceIndexRoute
  '/catalogos': typeof AuthenticatedCatalogosIndexRoute
  '/dashboard': typeof AuthenticatedDashboardIndexRoute
  '/documentos': typeof AuthenticatedDocumentosIndexRoute
  '/ejecucion': typeof AuthenticatedEjecucionIndexRoute
  '/integracion': typeof AuthenticatedIntegracionIndexRoute
  '/matriculas': typeof AuthenticatedMatriculasIndexRoute
  '/modificaciones': typeof AuthenticatedModificacionesIndexRoute
  '/nomina': typeof AuthenticatedNominaIndexRoute
  '/normatividad': typeof AuthenticatedNormatividadIndexRoute
  '/presupuesto': typeof AuthenticatedPresupuestoIndexRoute
  '/proyectos': typeof AuthenticatedProyectosIndexRoute
  '/sar-viaticos': typeof AuthenticatedSarViaticosIndexRoute
  '/admin/roles/$id': typeof AuthenticatedAdminRolesIdRoute
  '/admin/usuarios/$id': typeof AuthenticatedAdminUsuariosIdRoute
  '/sar-viaticos/sar/$id': typeof AuthenticatedSarViaticosSarIdRoute
  '/sar-viaticos/viaticos/$id': typeof AuthenticatedSarViaticosViaticosIdRoute
  '/admin/auditoria': typeof AuthenticatedAdminAuditoriaIndexRoute
  '/admin/roles': typeof AuthenticatedAdminRolesIndexRoute
  '/admin/usuarios': typeof AuthenticatedAdminUsuariosIndexRoute
  '/presupuesto/ejecucion-mensual': typeof AuthenticatedPresupuestoEjecucionMensualIndexRoute
  '/presupuesto/etapas': typeof AuthenticatedPresupuestoEtapasIndexRoute
  '/presupuesto/gastos': typeof AuthenticatedPresupuestoGastosIndexRoute
  '/presupuesto/ingresos': typeof AuthenticatedPresupuestoIngresosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteWithChildren
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/_auth/login': typeof AuthLoginRoute
  '/_authenticated/agenda': typeof AuthenticatedAgendaRouteWithChildren
  '/_authenticated/balance': typeof AuthenticatedBalanceRouteWithChildren
  '/_authenticated/catalogos': typeof AuthenticatedCatalogosRouteWithChildren
  '/_authenticated/ejecucion': typeof AuthenticatedEjecucionRouteWithChildren
  '/_authenticated/integracion': typeof AuthenticatedIntegracionRouteWithChildren
  '/_authenticated/nomina': typeof AuthenticatedNominaRouteWithChildren
  '/_authenticated/normatividad': typeof AuthenticatedNormatividadRouteWithChildren
  '/_authenticated/perfil': typeof AuthenticatedPerfilRouteWithChildren
  '/_authenticated/presupuesto': typeof AuthenticatedPresupuestoRouteWithChildren
  '/_authenticated/sar-viaticos': typeof AuthenticatedSarViaticosRouteWithChildren
  '/_authenticated/admin/vigencias': typeof AuthenticatedAdminVigenciasRoute
  '/_authenticated/agenda/eventos': typeof AuthenticatedAgendaEventosRoute
  '/_authenticated/agenda/mi-agenda': typeof AuthenticatedAgendaMiAgendaRoute
  '/_authenticated/balance/cierre': typeof AuthenticatedBalanceCierreRoute
  '/_authenticated/balance/conciliacion': typeof AuthenticatedBalanceConciliacionRoute
  '/_authenticated/balance/flujo-caja': typeof AuthenticatedBalanceFlujoCajaRoute
  '/_authenticated/balance/recaudos': typeof AuthenticatedBalanceRecaudosRoute
  '/_authenticated/balance/recursos': typeof AuthenticatedBalanceRecursosRoute
  '/_authenticated/catalogos/apoyos-matricula': typeof AuthenticatedCatalogosApoyosMatriculaRoute
  '/_authenticated/catalogos/conceptos-nomina': typeof AuthenticatedCatalogosConceptosNominaRoute
  '/_authenticated/catalogos/descuentos': typeof AuthenticatedCatalogosDescuentosRoute
  '/_authenticated/catalogos/fechas-limite': typeof AuthenticatedCatalogosFechasLimiteRoute
  '/_authenticated/catalogos/fuentes-recursos': typeof AuthenticatedCatalogosFuentesRecursosRoute
  '/_authenticated/catalogos/municipios': typeof AuthenticatedCatalogosMunicipiosRoute
  '/_authenticated/catalogos/periodos-academicos': typeof AuthenticatedCatalogosPeriodosAcademicosRoute
  '/_authenticated/catalogos/programas-academicos': typeof AuthenticatedCatalogosProgramasAcademicosRoute
  '/_authenticated/catalogos/rubros-gasto': typeof AuthenticatedCatalogosRubrosGastoRoute
  '/_authenticated/catalogos/rubros-ingreso': typeof AuthenticatedCatalogosRubrosIngresoRoute
  '/_authenticated/catalogos/tipos-proyecto': typeof AuthenticatedCatalogosTiposProyectoRoute
  '/_authenticated/catalogos/unidades-ejecutoras': typeof AuthenticatedCatalogosUnidadesEjecutorasRoute
  '/_authenticated/dashboard/informes': typeof AuthenticatedDashboardInformesRoute
  '/_authenticated/dashboard/seguimiento': typeof AuthenticatedDashboardSeguimientoRoute
  '/_authenticated/documentos/$id': typeof AuthenticatedDocumentosIdRoute
  '/_authenticated/ejecucion/avances': typeof AuthenticatedEjecucionAvancesRoute
  '/_authenticated/ejecucion/cdp': typeof AuthenticatedEjecucionCdpRoute
  '/_authenticated/ejecucion/op': typeof AuthenticatedEjecucionOpRoute
  '/_authenticated/ejecucion/radicacion': typeof AuthenticatedEjecucionRadicacionRoute
  '/_authenticated/ejecucion/reportes': typeof AuthenticatedEjecucionReportesRoute
  '/_authenticated/ejecucion/reservas': typeof AuthenticatedEjecucionReservasRoute
  '/_authenticated/ejecucion/rp': typeof AuthenticatedEjecucionRpRoute
  '/_authenticated/matriculas/becas-posgrado': typeof AuthenticatedMatriculasBecasPosgradoRoute
  '/_authenticated/matriculas/cobertura-pic': typeof AuthenticatedMatriculasCoberturaPicRoute
  '/_authenticated/matriculas/cohortes': typeof AuthenticatedMatriculasCohortesRoute
  '/_authenticated/matriculas/resumen': typeof AuthenticatedMatriculasResumenRoute
  '/_authenticated/matriculas/transferencias': typeof AuthenticatedMatriculasTransferenciasRoute
  '/_authenticated/modificaciones/$id': typeof AuthenticatedModificacionesIdRoute
  '/_authenticated/nomina/conciliacion': typeof AuthenticatedNominaConciliacionRoute
  '/_authenticated/nomina/costos-parafiscales': typeof AuthenticatedNominaCostosParafiscalesRoute
  '/_authenticated/nomina/empleados': typeof AuthenticatedNominaEmpleadosRoute
  '/_authenticated/nomina/liquidacion': typeof AuthenticatedNominaLiquidacionRoute
  '/_authenticated/nomina/plan-clases': typeof AuthenticatedNominaPlanClasesRoute
  '/_authenticated/nomina/puntos-salariales': typeof AuthenticatedNominaPuntosSalarialesRoute
  '/_authenticated/normatividad/normas': typeof AuthenticatedNormatividadNormasRoute
  '/_authenticated/perfil/2fa': typeof AuthenticatedPerfil2faRoute
  '/_authenticated/proyectos/$id': typeof AuthenticatedProyectosIdRoute
  '/_authenticated/sar-viaticos/sar': typeof AuthenticatedSarViaticosSarRouteWithChildren
  '/_authenticated/sar-viaticos/tarifas': typeof AuthenticatedSarViaticosTarifasRoute
  '/_authenticated/sar-viaticos/viaticos': typeof AuthenticatedSarViaticosViaticosRouteWithChildren
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/agenda/': typeof AuthenticatedAgendaIndexRoute
  '/_authenticated/balance/': typeof AuthenticatedBalanceIndexRoute
  '/_authenticated/catalogos/': typeof AuthenticatedCatalogosIndexRoute
  '/_authenticated/dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/_authenticated/documentos/': typeof AuthenticatedDocumentosIndexRoute
  '/_authenticated/ejecucion/': typeof AuthenticatedEjecucionIndexRoute
  '/_authenticated/integracion/': typeof AuthenticatedIntegracionIndexRoute
  '/_authenticated/matriculas/': typeof AuthenticatedMatriculasIndexRoute
  '/_authenticated/modificaciones/': typeof AuthenticatedModificacionesIndexRoute
  '/_authenticated/nomina/': typeof AuthenticatedNominaIndexRoute
  '/_authenticated/normatividad/': typeof AuthenticatedNormatividadIndexRoute
  '/_authenticated/presupuesto/': typeof AuthenticatedPresupuestoIndexRoute
  '/_authenticated/proyectos/': typeof AuthenticatedProyectosIndexRoute
  '/_authenticated/sar-viaticos/': typeof AuthenticatedSarViaticosIndexRoute
  '/_authenticated/admin/roles/$id': typeof AuthenticatedAdminRolesIdRoute
  '/_authenticated/admin/usuarios/$id': typeof AuthenticatedAdminUsuariosIdRoute
  '/_authenticated/sar-viaticos/sar/$id': typeof AuthenticatedSarViaticosSarIdRoute
  '/_authenticated/sar-viaticos/viaticos/$id': typeof AuthenticatedSarViaticosViaticosIdRoute
  '/_authenticated/admin/auditoria/': typeof AuthenticatedAdminAuditoriaIndexRoute
  '/_authenticated/admin/roles/': typeof AuthenticatedAdminRolesIndexRoute
  '/_authenticated/admin/usuarios/': typeof AuthenticatedAdminUsuariosIndexRoute
  '/_authenticated/presupuesto/ejecucion-mensual/': typeof AuthenticatedPresupuestoEjecucionMensualIndexRoute
  '/_authenticated/presupuesto/etapas/': typeof AuthenticatedPresupuestoEtapasIndexRoute
  '/_authenticated/presupuesto/gastos/': typeof AuthenticatedPresupuestoGastosIndexRoute
  '/_authenticated/presupuesto/ingresos/': typeof AuthenticatedPresupuestoIngresosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/agenda'
    | '/balance'
    | '/catalogos'
    | '/ejecucion'
    | '/integracion'
    | '/nomina'
    | '/normatividad'
    | '/perfil'
    | '/presupuesto'
    | '/sar-viaticos'
    | '/admin/vigencias'
    | '/agenda/eventos'
    | '/agenda/mi-agenda'
    | '/balance/cierre'
    | '/balance/conciliacion'
    | '/balance/flujo-caja'
    | '/balance/recaudos'
    | '/balance/recursos'
    | '/catalogos/apoyos-matricula'
    | '/catalogos/conceptos-nomina'
    | '/catalogos/descuentos'
    | '/catalogos/fechas-limite'
    | '/catalogos/fuentes-recursos'
    | '/catalogos/municipios'
    | '/catalogos/periodos-academicos'
    | '/catalogos/programas-academicos'
    | '/catalogos/rubros-gasto'
    | '/catalogos/rubros-ingreso'
    | '/catalogos/tipos-proyecto'
    | '/catalogos/unidades-ejecutoras'
    | '/dashboard/informes'
    | '/dashboard/seguimiento'
    | '/documentos/$id'
    | '/ejecucion/avances'
    | '/ejecucion/cdp'
    | '/ejecucion/op'
    | '/ejecucion/radicacion'
    | '/ejecucion/reportes'
    | '/ejecucion/reservas'
    | '/ejecucion/rp'
    | '/matriculas/becas-posgrado'
    | '/matriculas/cobertura-pic'
    | '/matriculas/cohortes'
    | '/matriculas/resumen'
    | '/matriculas/transferencias'
    | '/modificaciones/$id'
    | '/nomina/conciliacion'
    | '/nomina/costos-parafiscales'
    | '/nomina/empleados'
    | '/nomina/liquidacion'
    | '/nomina/plan-clases'
    | '/nomina/puntos-salariales'
    | '/normatividad/normas'
    | '/perfil/2fa'
    | '/proyectos/$id'
    | '/sar-viaticos/sar'
    | '/sar-viaticos/tarifas'
    | '/sar-viaticos/viaticos'
    | '/admin/'
    | '/agenda/'
    | '/balance/'
    | '/catalogos/'
    | '/dashboard/'
    | '/documentos/'
    | '/ejecucion/'
    | '/integracion/'
    | '/matriculas/'
    | '/modificaciones/'
    | '/nomina/'
    | '/normatividad/'
    | '/presupuesto/'
    | '/proyectos/'
    | '/sar-viaticos/'
    | '/admin/roles/$id'
    | '/admin/usuarios/$id'
    | '/sar-viaticos/sar/$id'
    | '/sar-viaticos/viaticos/$id'
    | '/admin/auditoria/'
    | '/admin/roles/'
    | '/admin/usuarios/'
    | '/presupuesto/ejecucion-mensual/'
    | '/presupuesto/etapas/'
    | '/presupuesto/gastos/'
    | '/presupuesto/ingresos/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/perfil'
    | '/admin/vigencias'
    | '/agenda/eventos'
    | '/agenda/mi-agenda'
    | '/balance/cierre'
    | '/balance/conciliacion'
    | '/balance/flujo-caja'
    | '/balance/recaudos'
    | '/balance/recursos'
    | '/catalogos/apoyos-matricula'
    | '/catalogos/conceptos-nomina'
    | '/catalogos/descuentos'
    | '/catalogos/fechas-limite'
    | '/catalogos/fuentes-recursos'
    | '/catalogos/municipios'
    | '/catalogos/periodos-academicos'
    | '/catalogos/programas-academicos'
    | '/catalogos/rubros-gasto'
    | '/catalogos/rubros-ingreso'
    | '/catalogos/tipos-proyecto'
    | '/catalogos/unidades-ejecutoras'
    | '/dashboard/informes'
    | '/dashboard/seguimiento'
    | '/documentos/$id'
    | '/ejecucion/avances'
    | '/ejecucion/cdp'
    | '/ejecucion/op'
    | '/ejecucion/radicacion'
    | '/ejecucion/reportes'
    | '/ejecucion/reservas'
    | '/ejecucion/rp'
    | '/matriculas/becas-posgrado'
    | '/matriculas/cobertura-pic'
    | '/matriculas/cohortes'
    | '/matriculas/resumen'
    | '/matriculas/transferencias'
    | '/modificaciones/$id'
    | '/nomina/conciliacion'
    | '/nomina/costos-parafiscales'
    | '/nomina/empleados'
    | '/nomina/liquidacion'
    | '/nomina/plan-clases'
    | '/nomina/puntos-salariales'
    | '/normatividad/normas'
    | '/perfil/2fa'
    | '/proyectos/$id'
    | '/sar-viaticos/sar'
    | '/sar-viaticos/tarifas'
    | '/sar-viaticos/viaticos'
    | '/admin'
    | '/agenda'
    | '/balance'
    | '/catalogos'
    | '/dashboard'
    | '/documentos'
    | '/ejecucion'
    | '/integracion'
    | '/matriculas'
    | '/modificaciones'
    | '/nomina'
    | '/normatividad'
    | '/presupuesto'
    | '/proyectos'
    | '/sar-viaticos'
    | '/admin/roles/$id'
    | '/admin/usuarios/$id'
    | '/sar-viaticos/sar/$id'
    | '/sar-viaticos/viaticos/$id'
    | '/admin/auditoria'
    | '/admin/roles'
    | '/admin/usuarios'
    | '/presupuesto/ejecucion-mensual'
    | '/presupuesto/etapas'
    | '/presupuesto/gastos'
    | '/presupuesto/ingresos'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/_authenticated'
    | '/_auth/login'
    | '/_authenticated/agenda'
    | '/_authenticated/balance'
    | '/_authenticated/catalogos'
    | '/_authenticated/ejecucion'
    | '/_authenticated/integracion'
    | '/_authenticated/nomina'
    | '/_authenticated/normatividad'
    | '/_authenticated/perfil'
    | '/_authenticated/presupuesto'
    | '/_authenticated/sar-viaticos'
    | '/_authenticated/admin/vigencias'
    | '/_authenticated/agenda/eventos'
    | '/_authenticated/agenda/mi-agenda'
    | '/_authenticated/balance/cierre'
    | '/_authenticated/balance/conciliacion'
    | '/_authenticated/balance/flujo-caja'
    | '/_authenticated/balance/recaudos'
    | '/_authenticated/balance/recursos'
    | '/_authenticated/catalogos/apoyos-matricula'
    | '/_authenticated/catalogos/conceptos-nomina'
    | '/_authenticated/catalogos/descuentos'
    | '/_authenticated/catalogos/fechas-limite'
    | '/_authenticated/catalogos/fuentes-recursos'
    | '/_authenticated/catalogos/municipios'
    | '/_authenticated/catalogos/periodos-academicos'
    | '/_authenticated/catalogos/programas-academicos'
    | '/_authenticated/catalogos/rubros-gasto'
    | '/_authenticated/catalogos/rubros-ingreso'
    | '/_authenticated/catalogos/tipos-proyecto'
    | '/_authenticated/catalogos/unidades-ejecutoras'
    | '/_authenticated/dashboard/informes'
    | '/_authenticated/dashboard/seguimiento'
    | '/_authenticated/documentos/$id'
    | '/_authenticated/ejecucion/avances'
    | '/_authenticated/ejecucion/cdp'
    | '/_authenticated/ejecucion/op'
    | '/_authenticated/ejecucion/radicacion'
    | '/_authenticated/ejecucion/reportes'
    | '/_authenticated/ejecucion/reservas'
    | '/_authenticated/ejecucion/rp'
    | '/_authenticated/matriculas/becas-posgrado'
    | '/_authenticated/matriculas/cobertura-pic'
    | '/_authenticated/matriculas/cohortes'
    | '/_authenticated/matriculas/resumen'
    | '/_authenticated/matriculas/transferencias'
    | '/_authenticated/modificaciones/$id'
    | '/_authenticated/nomina/conciliacion'
    | '/_authenticated/nomina/costos-parafiscales'
    | '/_authenticated/nomina/empleados'
    | '/_authenticated/nomina/liquidacion'
    | '/_authenticated/nomina/plan-clases'
    | '/_authenticated/nomina/puntos-salariales'
    | '/_authenticated/normatividad/normas'
    | '/_authenticated/perfil/2fa'
    | '/_authenticated/proyectos/$id'
    | '/_authenticated/sar-viaticos/sar'
    | '/_authenticated/sar-viaticos/tarifas'
    | '/_authenticated/sar-viaticos/viaticos'
    | '/_authenticated/admin/'
    | '/_authenticated/agenda/'
    | '/_authenticated/balance/'
    | '/_authenticated/catalogos/'
    | '/_authenticated/dashboard/'
    | '/_authenticated/documentos/'
    | '/_authenticated/ejecucion/'
    | '/_authenticated/integracion/'
    | '/_authenticated/matriculas/'
    | '/_authenticated/modificaciones/'
    | '/_authenticated/nomina/'
    | '/_authenticated/normatividad/'
    | '/_authenticated/presupuesto/'
    | '/_authenticated/proyectos/'
    | '/_authenticated/sar-viaticos/'
    | '/_authenticated/admin/roles/$id'
    | '/_authenticated/admin/usuarios/$id'
    | '/_authenticated/sar-viaticos/sar/$id'
    | '/_authenticated/sar-viaticos/viaticos/$id'
    | '/_authenticated/admin/auditoria/'
    | '/_authenticated/admin/roles/'
    | '/_authenticated/admin/usuarios/'
    | '/_authenticated/presupuesto/ejecucion-mensual/'
    | '/_authenticated/presupuesto/etapas/'
    | '/_authenticated/presupuesto/gastos/'
    | '/_authenticated/presupuesto/ingresos/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/sar-viaticos': {
      id: '/_authenticated/sar-viaticos'
      path: '/sar-viaticos'
      fullPath: '/sar-viaticos'
      preLoaderRoute: typeof AuthenticatedSarViaticosRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/presupuesto': {
      id: '/_authenticated/presupuesto'
      path: '/presupuesto'
      fullPath: '/presupuesto'
      preLoaderRoute: typeof AuthenticatedPresupuestoRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/perfil': {
      id: '/_authenticated/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof AuthenticatedPerfilRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/normatividad': {
      id: '/_authenticated/normatividad'
      path: '/normatividad'
      fullPath: '/normatividad'
      preLoaderRoute: typeof AuthenticatedNormatividadRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/nomina': {
      id: '/_authenticated/nomina'
      path: '/nomina'
      fullPath: '/nomina'
      preLoaderRoute: typeof AuthenticatedNominaRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/integracion': {
      id: '/_authenticated/integracion'
      path: '/integracion'
      fullPath: '/integracion'
      preLoaderRoute: typeof AuthenticatedIntegracionRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/ejecucion': {
      id: '/_authenticated/ejecucion'
      path: '/ejecucion'
      fullPath: '/ejecucion'
      preLoaderRoute: typeof AuthenticatedEjecucionRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/catalogos': {
      id: '/_authenticated/catalogos'
      path: '/catalogos'
      fullPath: '/catalogos'
      preLoaderRoute: typeof AuthenticatedCatalogosRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/balance': {
      id: '/_authenticated/balance'
      path: '/balance'
      fullPath: '/balance'
      preLoaderRoute: typeof AuthenticatedBalanceRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/agenda': {
      id: '/_authenticated/agenda'
      path: '/agenda'
      fullPath: '/agenda'
      preLoaderRoute: typeof AuthenticatedAgendaRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_authenticated/sar-viaticos/': {
      id: '/_authenticated/sar-viaticos/'
      path: '/'
      fullPath: '/sar-viaticos/'
      preLoaderRoute: typeof AuthenticatedSarViaticosIndexRouteImport
      parentRoute: typeof AuthenticatedSarViaticosRoute
    }
    '/_authenticated/proyectos/': {
      id: '/_authenticated/proyectos/'
      path: '/proyectos'
      fullPath: '/proyectos/'
      preLoaderRoute: typeof AuthenticatedProyectosIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/presupuesto/': {
      id: '/_authenticated/presupuesto/'
      path: '/'
      fullPath: '/presupuesto/'
      preLoaderRoute: typeof AuthenticatedPresupuestoIndexRouteImport
      parentRoute: typeof AuthenticatedPresupuestoRoute
    }
    '/_authenticated/normatividad/': {
      id: '/_authenticated/normatividad/'
      path: '/'
      fullPath: '/normatividad/'
      preLoaderRoute: typeof AuthenticatedNormatividadIndexRouteImport
      parentRoute: typeof AuthenticatedNormatividadRoute
    }
    '/_authenticated/nomina/': {
      id: '/_authenticated/nomina/'
      path: '/'
      fullPath: '/nomina/'
      preLoaderRoute: typeof AuthenticatedNominaIndexRouteImport
      parentRoute: typeof AuthenticatedNominaRoute
    }
    '/_authenticated/modificaciones/': {
      id: '/_authenticated/modificaciones/'
      path: '/modificaciones'
      fullPath: '/modificaciones/'
      preLoaderRoute: typeof AuthenticatedModificacionesIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/matriculas/': {
      id: '/_authenticated/matriculas/'
      path: '/matriculas'
      fullPath: '/matriculas/'
      preLoaderRoute: typeof AuthenticatedMatriculasIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/integracion/': {
      id: '/_authenticated/integracion/'
      path: '/'
      fullPath: '/integracion/'
      preLoaderRoute: typeof AuthenticatedIntegracionIndexRouteImport
      parentRoute: typeof AuthenticatedIntegracionRoute
    }
    '/_authenticated/ejecucion/': {
      id: '/_authenticated/ejecucion/'
      path: '/'
      fullPath: '/ejecucion/'
      preLoaderRoute: typeof AuthenticatedEjecucionIndexRouteImport
      parentRoute: typeof AuthenticatedEjecucionRoute
    }
    '/_authenticated/documentos/': {
      id: '/_authenticated/documentos/'
      path: '/documentos'
      fullPath: '/documentos/'
      preLoaderRoute: typeof AuthenticatedDocumentosIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard/': {
      id: '/_authenticated/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof AuthenticatedDashboardIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/catalogos/': {
      id: '/_authenticated/catalogos/'
      path: '/'
      fullPath: '/catalogos/'
      preLoaderRoute: typeof AuthenticatedCatalogosIndexRouteImport
      parentRoute: typeof AuthenticatedCatalogosRoute
    }
    '/_authenticated/balance/': {
      id: '/_authenticated/balance/'
      path: '/'
      fullPath: '/balance/'
      preLoaderRoute: typeof AuthenticatedBalanceIndexRouteImport
      parentRoute: typeof AuthenticatedBalanceRoute
    }
    '/_authenticated/agenda/': {
      id: '/_authenticated/agenda/'
      path: '/'
      fullPath: '/agenda/'
      preLoaderRoute: typeof AuthenticatedAgendaIndexRouteImport
      parentRoute: typeof AuthenticatedAgendaRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/sar-viaticos/viaticos': {
      id: '/_authenticated/sar-viaticos/viaticos'
      path: '/viaticos'
      fullPath: '/sar-viaticos/viaticos'
      preLoaderRoute: typeof AuthenticatedSarViaticosViaticosRouteImport
      parentRoute: typeof AuthenticatedSarViaticosRoute
    }
    '/_authenticated/sar-viaticos/tarifas': {
      id: '/_authenticated/sar-viaticos/tarifas'
      path: '/tarifas'
      fullPath: '/sar-viaticos/tarifas'
      preLoaderRoute: typeof AuthenticatedSarViaticosTarifasRouteImport
      parentRoute: typeof AuthenticatedSarViaticosRoute
    }
    '/_authenticated/sar-viaticos/sar': {
      id: '/_authenticated/sar-viaticos/sar'
      path: '/sar'
      fullPath: '/sar-viaticos/sar'
      preLoaderRoute: typeof AuthenticatedSarViaticosSarRouteImport
      parentRoute: typeof AuthenticatedSarViaticosRoute
    }
    '/_authenticated/proyectos/$id': {
      id: '/_authenticated/proyectos/$id'
      path: '/proyectos/$id'
      fullPath: '/proyectos/$id'
      preLoaderRoute: typeof AuthenticatedProyectosIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/perfil/2fa': {
      id: '/_authenticated/perfil/2fa'
      path: '/2fa'
      fullPath: '/perfil/2fa'
      preLoaderRoute: typeof AuthenticatedPerfil2faRouteImport
      parentRoute: typeof AuthenticatedPerfilRoute
    }
    '/_authenticated/normatividad/normas': {
      id: '/_authenticated/normatividad/normas'
      path: '/normas'
      fullPath: '/normatividad/normas'
      preLoaderRoute: typeof AuthenticatedNormatividadNormasRouteImport
      parentRoute: typeof AuthenticatedNormatividadRoute
    }
    '/_authenticated/nomina/puntos-salariales': {
      id: '/_authenticated/nomina/puntos-salariales'
      path: '/puntos-salariales'
      fullPath: '/nomina/puntos-salariales'
      preLoaderRoute: typeof AuthenticatedNominaPuntosSalarialesRouteImport
      parentRoute: typeof AuthenticatedNominaRoute
    }
    '/_authenticated/nomina/plan-clases': {
      id: '/_authenticated/nomina/plan-clases'
      path: '/plan-clases'
      fullPath: '/nomina/plan-clases'
      preLoaderRoute: typeof AuthenticatedNominaPlanClasesRouteImport
      parentRoute: typeof AuthenticatedNominaRoute
    }
    '/_authenticated/nomina/liquidacion': {
      id: '/_authenticated/nomina/liquidacion'
      path: '/liquidacion'
      fullPath: '/nomina/liquidacion'
      preLoaderRoute: typeof AuthenticatedNominaLiquidacionRouteImport
      parentRoute: typeof AuthenticatedNominaRoute
    }
    '/_authenticated/nomina/empleados': {
      id: '/_authenticated/nomina/empleados'
      path: '/empleados'
      fullPath: '/nomina/empleados'
      preLoaderRoute: typeof AuthenticatedNominaEmpleadosRouteImport
      parentRoute: typeof AuthenticatedNominaRoute
    }
    '/_authenticated/nomina/costos-parafiscales': {
      id: '/_authenticated/nomina/costos-parafiscales'
      path: '/costos-parafiscales'
      fullPath: '/nomina/costos-parafiscales'
      preLoaderRoute: typeof AuthenticatedNominaCostosParafiscalesRouteImport
      parentRoute: typeof AuthenticatedNominaRoute
    }
    '/_authenticated/nomina/conciliacion': {
      id: '/_authenticated/nomina/conciliacion'
      path: '/conciliacion'
      fullPath: '/nomina/conciliacion'
      preLoaderRoute: typeof AuthenticatedNominaConciliacionRouteImport
      parentRoute: typeof AuthenticatedNominaRoute
    }
    '/_authenticated/modificaciones/$id': {
      id: '/_authenticated/modificaciones/$id'
      path: '/modificaciones/$id'
      fullPath: '/modificaciones/$id'
      preLoaderRoute: typeof AuthenticatedModificacionesIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/matriculas/transferencias': {
      id: '/_authenticated/matriculas/transferencias'
      path: '/matriculas/transferencias'
      fullPath: '/matriculas/transferencias'
      preLoaderRoute: typeof AuthenticatedMatriculasTransferenciasRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/matriculas/resumen': {
      id: '/_authenticated/matriculas/resumen'
      path: '/matriculas/resumen'
      fullPath: '/matriculas/resumen'
      preLoaderRoute: typeof AuthenticatedMatriculasResumenRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/matriculas/cohortes': {
      id: '/_authenticated/matriculas/cohortes'
      path: '/matriculas/cohortes'
      fullPath: '/matriculas/cohortes'
      preLoaderRoute: typeof AuthenticatedMatriculasCohortesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/matriculas/cobertura-pic': {
      id: '/_authenticated/matriculas/cobertura-pic'
      path: '/matriculas/cobertura-pic'
      fullPath: '/matriculas/cobertura-pic'
      preLoaderRoute: typeof AuthenticatedMatriculasCoberturaPicRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/matriculas/becas-posgrado': {
      id: '/_authenticated/matriculas/becas-posgrado'
      path: '/matriculas/becas-posgrado'
      fullPath: '/matriculas/becas-posgrado'
      preLoaderRoute: typeof AuthenticatedMatriculasBecasPosgradoRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/ejecucion/rp': {
      id: '/_authenticated/ejecucion/rp'
      path: '/rp'
      fullPath: '/ejecucion/rp'
      preLoaderRoute: typeof AuthenticatedEjecucionRpRouteImport
      parentRoute: typeof AuthenticatedEjecucionRoute
    }
    '/_authenticated/ejecucion/reservas': {
      id: '/_authenticated/ejecucion/reservas'
      path: '/reservas'
      fullPath: '/ejecucion/reservas'
      preLoaderRoute: typeof AuthenticatedEjecucionReservasRouteImport
      parentRoute: typeof AuthenticatedEjecucionRoute
    }
    '/_authenticated/ejecucion/reportes': {
      id: '/_authenticated/ejecucion/reportes'
      path: '/reportes'
      fullPath: '/ejecucion/reportes'
      preLoaderRoute: typeof AuthenticatedEjecucionReportesRouteImport
      parentRoute: typeof AuthenticatedEjecucionRoute
    }
    '/_authenticated/ejecucion/radicacion': {
      id: '/_authenticated/ejecucion/radicacion'
      path: '/radicacion'
      fullPath: '/ejecucion/radicacion'
      preLoaderRoute: typeof AuthenticatedEjecucionRadicacionRouteImport
      parentRoute: typeof AuthenticatedEjecucionRoute
    }
    '/_authenticated/ejecucion/op': {
      id: '/_authenticated/ejecucion/op'
      path: '/op'
      fullPath: '/ejecucion/op'
      preLoaderRoute: typeof AuthenticatedEjecucionOpRouteImport
      parentRoute: typeof AuthenticatedEjecucionRoute
    }
    '/_authenticated/ejecucion/cdp': {
      id: '/_authenticated/ejecucion/cdp'
      path: '/cdp'
      fullPath: '/ejecucion/cdp'
      preLoaderRoute: typeof AuthenticatedEjecucionCdpRouteImport
      parentRoute: typeof AuthenticatedEjecucionRoute
    }
    '/_authenticated/ejecucion/avances': {
      id: '/_authenticated/ejecucion/avances'
      path: '/avances'
      fullPath: '/ejecucion/avances'
      preLoaderRoute: typeof AuthenticatedEjecucionAvancesRouteImport
      parentRoute: typeof AuthenticatedEjecucionRoute
    }
    '/_authenticated/documentos/$id': {
      id: '/_authenticated/documentos/$id'
      path: '/documentos/$id'
      fullPath: '/documentos/$id'
      preLoaderRoute: typeof AuthenticatedDocumentosIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard/seguimiento': {
      id: '/_authenticated/dashboard/seguimiento'
      path: '/dashboard/seguimiento'
      fullPath: '/dashboard/seguimiento'
      preLoaderRoute: typeof AuthenticatedDashboardSeguimientoRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard/informes': {
      id: '/_authenticated/dashboard/informes'
      path: '/dashboard/informes'
      fullPath: '/dashboard/informes'
      preLoaderRoute: typeof AuthenticatedDashboardInformesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/catalogos/unidades-ejecutoras': {
      id: '/_authenticated/catalogos/unidades-ejecutoras'
      path: '/unidades-ejecutoras'
      fullPath: '/catalogos/unidades-ejecutoras'
      preLoaderRoute: typeof AuthenticatedCatalogosUnidadesEjecutorasRouteImport
      parentRoute: typeof AuthenticatedCatalogosRoute
    }
    '/_authenticated/catalogos/tipos-proyecto': {
      id: '/_authenticated/catalogos/tipos-proyecto'
      path: '/tipos-proyecto'
      fullPath: '/catalogos/tipos-proyecto'
      preLoaderRoute: typeof AuthenticatedCatalogosTiposProyectoRouteImport
      parentRoute: typeof AuthenticatedCatalogosRoute
    }
    '/_authenticated/catalogos/rubros-ingreso': {
      id: '/_authenticated/catalogos/rubros-ingreso'
      path: '/rubros-ingreso'
      fullPath: '/catalogos/rubros-ingreso'
      preLoaderRoute: typeof AuthenticatedCatalogosRubrosIngresoRouteImport
      parentRoute: typeof AuthenticatedCatalogosRoute
    }
    '/_authenticated/catalogos/rubros-gasto': {
      id: '/_authenticated/catalogos/rubros-gasto'
      path: '/rubros-gasto'
      fullPath: '/catalogos/rubros-gasto'
      preLoaderRoute: typeof AuthenticatedCatalogosRubrosGastoRouteImport
      parentRoute: typeof AuthenticatedCatalogosRoute
    }
    '/_authenticated/catalogos/programas-academicos': {
      id: '/_authenticated/catalogos/programas-academicos'
      path: '/programas-academicos'
      fullPath: '/catalogos/programas-academicos'
      preLoaderRoute: typeof AuthenticatedCatalogosProgramasAcademicosRouteImport
      parentRoute: typeof AuthenticatedCatalogosRoute
    }
    '/_authenticated/catalogos/periodos-academicos': {
      id: '/_authenticated/catalogos/periodos-academicos'
      path: '/periodos-academicos'
      fullPath: '/catalogos/periodos-academicos'
      preLoaderRoute: typeof AuthenticatedCatalogosPeriodosAcademicosRouteImport
      parentRoute: typeof AuthenticatedCatalogosRoute
    }
    '/_authenticated/catalogos/municipios': {
      id: '/_authenticated/catalogos/municipios'
      path: '/municipios'
      fullPath: '/catalogos/municipios'
      preLoaderRoute: typeof AuthenticatedCatalogosMunicipiosRouteImport
      parentRoute: typeof AuthenticatedCatalogosRoute
    }
    '/_authenticated/catalogos/fuentes-recursos': {
      id: '/_authenticated/catalogos/fuentes-recursos'
      path: '/fuentes-recursos'
      fullPath: '/catalogos/fuentes-recursos'
      preLoaderRoute: typeof AuthenticatedCatalogosFuentesRecursosRouteImport
      parentRoute: typeof AuthenticatedCatalogosRoute
    }
    '/_authenticated/catalogos/fechas-limite': {
      id: '/_authenticated/catalogos/fechas-limite'
      path: '/fechas-limite'
      fullPath: '/catalogos/fechas-limite'
      preLoaderRoute: typeof AuthenticatedCatalogosFechasLimiteRouteImport
      parentRoute: typeof AuthenticatedCatalogosRoute
    }
    '/_authenticated/catalogos/descuentos': {
      id: '/_authenticated/catalogos/descuentos'
      path: '/descuentos'
      fullPath: '/catalogos/descuentos'
      preLoaderRoute: typeof AuthenticatedCatalogosDescuentosRouteImport
      parentRoute: typeof AuthenticatedCatalogosRoute
    }
    '/_authenticated/catalogos/conceptos-nomina': {
      id: '/_authenticated/catalogos/conceptos-nomina'
      path: '/conceptos-nomina'
      fullPath: '/catalogos/conceptos-nomina'
      preLoaderRoute: typeof AuthenticatedCatalogosConceptosNominaRouteImport
      parentRoute: typeof AuthenticatedCatalogosRoute
    }
    '/_authenticated/catalogos/apoyos-matricula': {
      id: '/_authenticated/catalogos/apoyos-matricula'
      path: '/apoyos-matricula'
      fullPath: '/catalogos/apoyos-matricula'
      preLoaderRoute: typeof AuthenticatedCatalogosApoyosMatriculaRouteImport
      parentRoute: typeof AuthenticatedCatalogosRoute
    }
    '/_authenticated/balance/recursos': {
      id: '/_authenticated/balance/recursos'
      path: '/recursos'
      fullPath: '/balance/recursos'
      preLoaderRoute: typeof AuthenticatedBalanceRecursosRouteImport
      parentRoute: typeof AuthenticatedBalanceRoute
    }
    '/_authenticated/balance/recaudos': {
      id: '/_authenticated/balance/recaudos'
      path: '/recaudos'
      fullPath: '/balance/recaudos'
      preLoaderRoute: typeof AuthenticatedBalanceRecaudosRouteImport
      parentRoute: typeof AuthenticatedBalanceRoute
    }
    '/_authenticated/balance/flujo-caja': {
      id: '/_authenticated/balance/flujo-caja'
      path: '/flujo-caja'
      fullPath: '/balance/flujo-caja'
      preLoaderRoute: typeof AuthenticatedBalanceFlujoCajaRouteImport
      parentRoute: typeof AuthenticatedBalanceRoute
    }
    '/_authenticated/balance/conciliacion': {
      id: '/_authenticated/balance/conciliacion'
      path: '/conciliacion'
      fullPath: '/balance/conciliacion'
      preLoaderRoute: typeof AuthenticatedBalanceConciliacionRouteImport
      parentRoute: typeof AuthenticatedBalanceRoute
    }
    '/_authenticated/balance/cierre': {
      id: '/_authenticated/balance/cierre'
      path: '/cierre'
      fullPath: '/balance/cierre'
      preLoaderRoute: typeof AuthenticatedBalanceCierreRouteImport
      parentRoute: typeof AuthenticatedBalanceRoute
    }
    '/_authenticated/agenda/mi-agenda': {
      id: '/_authenticated/agenda/mi-agenda'
      path: '/mi-agenda'
      fullPath: '/agenda/mi-agenda'
      preLoaderRoute: typeof AuthenticatedAgendaMiAgendaRouteImport
      parentRoute: typeof AuthenticatedAgendaRoute
    }
    '/_authenticated/agenda/eventos': {
      id: '/_authenticated/agenda/eventos'
      path: '/eventos'
      fullPath: '/agenda/eventos'
      preLoaderRoute: typeof AuthenticatedAgendaEventosRouteImport
      parentRoute: typeof AuthenticatedAgendaRoute
    }
    '/_authenticated/admin/vigencias': {
      id: '/_authenticated/admin/vigencias'
      path: '/admin/vigencias'
      fullPath: '/admin/vigencias'
      preLoaderRoute: typeof AuthenticatedAdminVigenciasRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/presupuesto/ingresos/': {
      id: '/_authenticated/presupuesto/ingresos/'
      path: '/ingresos'
      fullPath: '/presupuesto/ingresos/'
      preLoaderRoute: typeof AuthenticatedPresupuestoIngresosIndexRouteImport
      parentRoute: typeof AuthenticatedPresupuestoRoute
    }
    '/_authenticated/presupuesto/gastos/': {
      id: '/_authenticated/presupuesto/gastos/'
      path: '/gastos'
      fullPath: '/presupuesto/gastos/'
      preLoaderRoute: typeof AuthenticatedPresupuestoGastosIndexRouteImport
      parentRoute: typeof AuthenticatedPresupuestoRoute
    }
    '/_authenticated/presupuesto/etapas/': {
      id: '/_authenticated/presupuesto/etapas/'
      path: '/etapas'
      fullPath: '/presupuesto/etapas/'
      preLoaderRoute: typeof AuthenticatedPresupuestoEtapasIndexRouteImport
      parentRoute: typeof AuthenticatedPresupuestoRoute
    }
    '/_authenticated/presupuesto/ejecucion-mensual/': {
      id: '/_authenticated/presupuesto/ejecucion-mensual/'
      path: '/ejecucion-mensual'
      fullPath: '/presupuesto/ejecucion-mensual/'
      preLoaderRoute: typeof AuthenticatedPresupuestoEjecucionMensualIndexRouteImport
      parentRoute: typeof AuthenticatedPresupuestoRoute
    }
    '/_authenticated/admin/usuarios/': {
      id: '/_authenticated/admin/usuarios/'
      path: '/admin/usuarios'
      fullPath: '/admin/usuarios/'
      preLoaderRoute: typeof AuthenticatedAdminUsuariosIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/roles/': {
      id: '/_authenticated/admin/roles/'
      path: '/admin/roles'
      fullPath: '/admin/roles/'
      preLoaderRoute: typeof AuthenticatedAdminRolesIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/auditoria/': {
      id: '/_authenticated/admin/auditoria/'
      path: '/admin/auditoria'
      fullPath: '/admin/auditoria/'
      preLoaderRoute: typeof AuthenticatedAdminAuditoriaIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/sar-viaticos/viaticos/$id': {
      id: '/_authenticated/sar-viaticos/viaticos/$id'
      path: '/$id'
      fullPath: '/sar-viaticos/viaticos/$id'
      preLoaderRoute: typeof AuthenticatedSarViaticosViaticosIdRouteImport
      parentRoute: typeof AuthenticatedSarViaticosViaticosRoute
    }
    '/_authenticated/sar-viaticos/sar/$id': {
      id: '/_authenticated/sar-viaticos/sar/$id'
      path: '/$id'
      fullPath: '/sar-viaticos/sar/$id'
      preLoaderRoute: typeof AuthenticatedSarViaticosSarIdRouteImport
      parentRoute: typeof AuthenticatedSarViaticosSarRoute
    }
    '/_authenticated/admin/usuarios/$id': {
      id: '/_authenticated/admin/usuarios/$id'
      path: '/admin/usuarios/$id'
      fullPath: '/admin/usuarios/$id'
      preLoaderRoute: typeof AuthenticatedAdminUsuariosIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/roles/$id': {
      id: '/_authenticated/admin/roles/$id'
      path: '/admin/roles/$id'
      fullPath: '/admin/roles/$id'
      preLoaderRoute: typeof AuthenticatedAdminRolesIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface AuthenticatedAgendaRouteChildren {
  AuthenticatedAgendaEventosRoute: typeof AuthenticatedAgendaEventosRoute
  AuthenticatedAgendaMiAgendaRoute: typeof AuthenticatedAgendaMiAgendaRoute
  AuthenticatedAgendaIndexRoute: typeof AuthenticatedAgendaIndexRoute
}

const AuthenticatedAgendaRouteChildren: AuthenticatedAgendaRouteChildren = {
  AuthenticatedAgendaEventosRoute: AuthenticatedAgendaEventosRoute,
  AuthenticatedAgendaMiAgendaRoute: AuthenticatedAgendaMiAgendaRoute,
  AuthenticatedAgendaIndexRoute: AuthenticatedAgendaIndexRoute,
}

const AuthenticatedAgendaRouteWithChildren =
  AuthenticatedAgendaRoute._addFileChildren(AuthenticatedAgendaRouteChildren)

interface AuthenticatedBalanceRouteChildren {
  AuthenticatedBalanceCierreRoute: typeof AuthenticatedBalanceCierreRoute
  AuthenticatedBalanceConciliacionRoute: typeof AuthenticatedBalanceConciliacionRoute
  AuthenticatedBalanceFlujoCajaRoute: typeof AuthenticatedBalanceFlujoCajaRoute
  AuthenticatedBalanceRecaudosRoute: typeof AuthenticatedBalanceRecaudosRoute
  AuthenticatedBalanceRecursosRoute: typeof AuthenticatedBalanceRecursosRoute
  AuthenticatedBalanceIndexRoute: typeof AuthenticatedBalanceIndexRoute
}

const AuthenticatedBalanceRouteChildren: AuthenticatedBalanceRouteChildren = {
  AuthenticatedBalanceCierreRoute: AuthenticatedBalanceCierreRoute,
  AuthenticatedBalanceConciliacionRoute: AuthenticatedBalanceConciliacionRoute,
  AuthenticatedBalanceFlujoCajaRoute: AuthenticatedBalanceFlujoCajaRoute,
  AuthenticatedBalanceRecaudosRoute: AuthenticatedBalanceRecaudosRoute,
  AuthenticatedBalanceRecursosRoute: AuthenticatedBalanceRecursosRoute,
  AuthenticatedBalanceIndexRoute: AuthenticatedBalanceIndexRoute,
}

const AuthenticatedBalanceRouteWithChildren =
  AuthenticatedBalanceRoute._addFileChildren(AuthenticatedBalanceRouteChildren)

interface AuthenticatedCatalogosRouteChildren {
  AuthenticatedCatalogosApoyosMatriculaRoute: typeof AuthenticatedCatalogosApoyosMatriculaRoute
  AuthenticatedCatalogosConceptosNominaRoute: typeof AuthenticatedCatalogosConceptosNominaRoute
  AuthenticatedCatalogosDescuentosRoute: typeof AuthenticatedCatalogosDescuentosRoute
  AuthenticatedCatalogosFechasLimiteRoute: typeof AuthenticatedCatalogosFechasLimiteRoute
  AuthenticatedCatalogosFuentesRecursosRoute: typeof AuthenticatedCatalogosFuentesRecursosRoute
  AuthenticatedCatalogosMunicipiosRoute: typeof AuthenticatedCatalogosMunicipiosRoute
  AuthenticatedCatalogosPeriodosAcademicosRoute: typeof AuthenticatedCatalogosPeriodosAcademicosRoute
  AuthenticatedCatalogosProgramasAcademicosRoute: typeof AuthenticatedCatalogosProgramasAcademicosRoute
  AuthenticatedCatalogosRubrosGastoRoute: typeof AuthenticatedCatalogosRubrosGastoRoute
  AuthenticatedCatalogosRubrosIngresoRoute: typeof AuthenticatedCatalogosRubrosIngresoRoute
  AuthenticatedCatalogosTiposProyectoRoute: typeof AuthenticatedCatalogosTiposProyectoRoute
  AuthenticatedCatalogosUnidadesEjecutorasRoute: typeof AuthenticatedCatalogosUnidadesEjecutorasRoute
  AuthenticatedCatalogosIndexRoute: typeof AuthenticatedCatalogosIndexRoute
}

const AuthenticatedCatalogosRouteChildren: AuthenticatedCatalogosRouteChildren =
  {
    AuthenticatedCatalogosApoyosMatriculaRoute:
      AuthenticatedCatalogosApoyosMatriculaRoute,
    AuthenticatedCatalogosConceptosNominaRoute:
      AuthenticatedCatalogosConceptosNominaRoute,
    AuthenticatedCatalogosDescuentosRoute:
      AuthenticatedCatalogosDescuentosRoute,
    AuthenticatedCatalogosFechasLimiteRoute:
      AuthenticatedCatalogosFechasLimiteRoute,
    AuthenticatedCatalogosFuentesRecursosRoute:
      AuthenticatedCatalogosFuentesRecursosRoute,
    AuthenticatedCatalogosMunicipiosRoute:
      AuthenticatedCatalogosMunicipiosRoute,
    AuthenticatedCatalogosPeriodosAcademicosRoute:
      AuthenticatedCatalogosPeriodosAcademicosRoute,
    AuthenticatedCatalogosProgramasAcademicosRoute:
      AuthenticatedCatalogosProgramasAcademicosRoute,
    AuthenticatedCatalogosRubrosGastoRoute:
      AuthenticatedCatalogosRubrosGastoRoute,
    AuthenticatedCatalogosRubrosIngresoRoute:
      AuthenticatedCatalogosRubrosIngresoRoute,
    AuthenticatedCatalogosTiposProyectoRoute:
      AuthenticatedCatalogosTiposProyectoRoute,
    AuthenticatedCatalogosUnidadesEjecutorasRoute:
      AuthenticatedCatalogosUnidadesEjecutorasRoute,
    AuthenticatedCatalogosIndexRoute: AuthenticatedCatalogosIndexRoute,
  }

const AuthenticatedCatalogosRouteWithChildren =
  AuthenticatedCatalogosRoute._addFileChildren(
    AuthenticatedCatalogosRouteChildren,
  )

interface AuthenticatedEjecucionRouteChildren {
  AuthenticatedEjecucionAvancesRoute: typeof AuthenticatedEjecucionAvancesRoute
  AuthenticatedEjecucionCdpRoute: typeof AuthenticatedEjecucionCdpRoute
  AuthenticatedEjecucionOpRoute: typeof AuthenticatedEjecucionOpRoute
  AuthenticatedEjecucionRadicacionRoute: typeof AuthenticatedEjecucionRadicacionRoute
  AuthenticatedEjecucionReportesRoute: typeof AuthenticatedEjecucionReportesRoute
  AuthenticatedEjecucionReservasRoute: typeof AuthenticatedEjecucionReservasRoute
  AuthenticatedEjecucionRpRoute: typeof AuthenticatedEjecucionRpRoute
  AuthenticatedEjecucionIndexRoute: typeof AuthenticatedEjecucionIndexRoute
}

const AuthenticatedEjecucionRouteChildren: AuthenticatedEjecucionRouteChildren =
  {
    AuthenticatedEjecucionAvancesRoute: AuthenticatedEjecucionAvancesRoute,
    AuthenticatedEjecucionCdpRoute: AuthenticatedEjecucionCdpRoute,
    AuthenticatedEjecucionOpRoute: AuthenticatedEjecucionOpRoute,
    AuthenticatedEjecucionRadicacionRoute:
      AuthenticatedEjecucionRadicacionRoute,
    AuthenticatedEjecucionReportesRoute: AuthenticatedEjecucionReportesRoute,
    AuthenticatedEjecucionReservasRoute: AuthenticatedEjecucionReservasRoute,
    AuthenticatedEjecucionRpRoute: AuthenticatedEjecucionRpRoute,
    AuthenticatedEjecucionIndexRoute: AuthenticatedEjecucionIndexRoute,
  }

const AuthenticatedEjecucionRouteWithChildren =
  AuthenticatedEjecucionRoute._addFileChildren(
    AuthenticatedEjecucionRouteChildren,
  )

interface AuthenticatedIntegracionRouteChildren {
  AuthenticatedIntegracionIndexRoute: typeof AuthenticatedIntegracionIndexRoute
}

const AuthenticatedIntegracionRouteChildren: AuthenticatedIntegracionRouteChildren =
  {
    AuthenticatedIntegracionIndexRoute: AuthenticatedIntegracionIndexRoute,
  }

const AuthenticatedIntegracionRouteWithChildren =
  AuthenticatedIntegracionRoute._addFileChildren(
    AuthenticatedIntegracionRouteChildren,
  )

interface AuthenticatedNominaRouteChildren {
  AuthenticatedNominaConciliacionRoute: typeof AuthenticatedNominaConciliacionRoute
  AuthenticatedNominaCostosParafiscalesRoute: typeof AuthenticatedNominaCostosParafiscalesRoute
  AuthenticatedNominaEmpleadosRoute: typeof AuthenticatedNominaEmpleadosRoute
  AuthenticatedNominaLiquidacionRoute: typeof AuthenticatedNominaLiquidacionRoute
  AuthenticatedNominaPlanClasesRoute: typeof AuthenticatedNominaPlanClasesRoute
  AuthenticatedNominaPuntosSalarialesRoute: typeof AuthenticatedNominaPuntosSalarialesRoute
  AuthenticatedNominaIndexRoute: typeof AuthenticatedNominaIndexRoute
}

const AuthenticatedNominaRouteChildren: AuthenticatedNominaRouteChildren = {
  AuthenticatedNominaConciliacionRoute: AuthenticatedNominaConciliacionRoute,
  AuthenticatedNominaCostosParafiscalesRoute:
    AuthenticatedNominaCostosParafiscalesRoute,
  AuthenticatedNominaEmpleadosRoute: AuthenticatedNominaEmpleadosRoute,
  AuthenticatedNominaLiquidacionRoute: AuthenticatedNominaLiquidacionRoute,
  AuthenticatedNominaPlanClasesRoute: AuthenticatedNominaPlanClasesRoute,
  AuthenticatedNominaPuntosSalarialesRoute:
    AuthenticatedNominaPuntosSalarialesRoute,
  AuthenticatedNominaIndexRoute: AuthenticatedNominaIndexRoute,
}

const AuthenticatedNominaRouteWithChildren =
  AuthenticatedNominaRoute._addFileChildren(AuthenticatedNominaRouteChildren)

interface AuthenticatedNormatividadRouteChildren {
  AuthenticatedNormatividadNormasRoute: typeof AuthenticatedNormatividadNormasRoute
  AuthenticatedNormatividadIndexRoute: typeof AuthenticatedNormatividadIndexRoute
}

const AuthenticatedNormatividadRouteChildren: AuthenticatedNormatividadRouteChildren =
  {
    AuthenticatedNormatividadNormasRoute: AuthenticatedNormatividadNormasRoute,
    AuthenticatedNormatividadIndexRoute: AuthenticatedNormatividadIndexRoute,
  }

const AuthenticatedNormatividadRouteWithChildren =
  AuthenticatedNormatividadRoute._addFileChildren(
    AuthenticatedNormatividadRouteChildren,
  )

interface AuthenticatedPerfilRouteChildren {
  AuthenticatedPerfil2faRoute: typeof AuthenticatedPerfil2faRoute
}

const AuthenticatedPerfilRouteChildren: AuthenticatedPerfilRouteChildren = {
  AuthenticatedPerfil2faRoute: AuthenticatedPerfil2faRoute,
}

const AuthenticatedPerfilRouteWithChildren =
  AuthenticatedPerfilRoute._addFileChildren(AuthenticatedPerfilRouteChildren)

interface AuthenticatedPresupuestoRouteChildren {
  AuthenticatedPresupuestoIndexRoute: typeof AuthenticatedPresupuestoIndexRoute
  AuthenticatedPresupuestoEjecucionMensualIndexRoute: typeof AuthenticatedPresupuestoEjecucionMensualIndexRoute
  AuthenticatedPresupuestoEtapasIndexRoute: typeof AuthenticatedPresupuestoEtapasIndexRoute
  AuthenticatedPresupuestoGastosIndexRoute: typeof AuthenticatedPresupuestoGastosIndexRoute
  AuthenticatedPresupuestoIngresosIndexRoute: typeof AuthenticatedPresupuestoIngresosIndexRoute
}

const AuthenticatedPresupuestoRouteChildren: AuthenticatedPresupuestoRouteChildren =
  {
    AuthenticatedPresupuestoIndexRoute: AuthenticatedPresupuestoIndexRoute,
    AuthenticatedPresupuestoEjecucionMensualIndexRoute:
      AuthenticatedPresupuestoEjecucionMensualIndexRoute,
    AuthenticatedPresupuestoEtapasIndexRoute:
      AuthenticatedPresupuestoEtapasIndexRoute,
    AuthenticatedPresupuestoGastosIndexRoute:
      AuthenticatedPresupuestoGastosIndexRoute,
    AuthenticatedPresupuestoIngresosIndexRoute:
      AuthenticatedPresupuestoIngresosIndexRoute,
  }

const AuthenticatedPresupuestoRouteWithChildren =
  AuthenticatedPresupuestoRoute._addFileChildren(
    AuthenticatedPresupuestoRouteChildren,
  )

interface AuthenticatedSarViaticosSarRouteChildren {
  AuthenticatedSarViaticosSarIdRoute: typeof AuthenticatedSarViaticosSarIdRoute
}

const AuthenticatedSarViaticosSarRouteChildren: AuthenticatedSarViaticosSarRouteChildren =
  {
    AuthenticatedSarViaticosSarIdRoute: AuthenticatedSarViaticosSarIdRoute,
  }

const AuthenticatedSarViaticosSarRouteWithChildren =
  AuthenticatedSarViaticosSarRoute._addFileChildren(
    AuthenticatedSarViaticosSarRouteChildren,
  )

interface AuthenticatedSarViaticosViaticosRouteChildren {
  AuthenticatedSarViaticosViaticosIdRoute: typeof AuthenticatedSarViaticosViaticosIdRoute
}

const AuthenticatedSarViaticosViaticosRouteChildren: AuthenticatedSarViaticosViaticosRouteChildren =
  {
    AuthenticatedSarViaticosViaticosIdRoute:
      AuthenticatedSarViaticosViaticosIdRoute,
  }

const AuthenticatedSarViaticosViaticosRouteWithChildren =
  AuthenticatedSarViaticosViaticosRoute._addFileChildren(
    AuthenticatedSarViaticosViaticosRouteChildren,
  )

interface AuthenticatedSarViaticosRouteChildren {
  AuthenticatedSarViaticosSarRoute: typeof AuthenticatedSarViaticosSarRouteWithChildren
  AuthenticatedSarViaticosTarifasRoute: typeof AuthenticatedSarViaticosTarifasRoute
  AuthenticatedSarViaticosViaticosRoute: typeof AuthenticatedSarViaticosViaticosRouteWithChildren
  AuthenticatedSarViaticosIndexRoute: typeof AuthenticatedSarViaticosIndexRoute
}

const AuthenticatedSarViaticosRouteChildren: AuthenticatedSarViaticosRouteChildren =
  {
    AuthenticatedSarViaticosSarRoute:
      AuthenticatedSarViaticosSarRouteWithChildren,
    AuthenticatedSarViaticosTarifasRoute: AuthenticatedSarViaticosTarifasRoute,
    AuthenticatedSarViaticosViaticosRoute:
      AuthenticatedSarViaticosViaticosRouteWithChildren,
    AuthenticatedSarViaticosIndexRoute: AuthenticatedSarViaticosIndexRoute,
  }

const AuthenticatedSarViaticosRouteWithChildren =
  AuthenticatedSarViaticosRoute._addFileChildren(
    AuthenticatedSarViaticosRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedAgendaRoute: typeof AuthenticatedAgendaRouteWithChildren
  AuthenticatedBalanceRoute: typeof AuthenticatedBalanceRouteWithChildren
  AuthenticatedCatalogosRoute: typeof AuthenticatedCatalogosRouteWithChildren
  AuthenticatedEjecucionRoute: typeof AuthenticatedEjecucionRouteWithChildren
  AuthenticatedIntegracionRoute: typeof AuthenticatedIntegracionRouteWithChildren
  AuthenticatedNominaRoute: typeof AuthenticatedNominaRouteWithChildren
  AuthenticatedNormatividadRoute: typeof AuthenticatedNormatividadRouteWithChildren
  AuthenticatedPerfilRoute: typeof AuthenticatedPerfilRouteWithChildren
  AuthenticatedPresupuestoRoute: typeof AuthenticatedPresupuestoRouteWithChildren
  AuthenticatedSarViaticosRoute: typeof AuthenticatedSarViaticosRouteWithChildren
  AuthenticatedAdminVigenciasRoute: typeof AuthenticatedAdminVigenciasRoute
  AuthenticatedDashboardInformesRoute: typeof AuthenticatedDashboardInformesRoute
  AuthenticatedDashboardSeguimientoRoute: typeof AuthenticatedDashboardSeguimientoRoute
  AuthenticatedDocumentosIdRoute: typeof AuthenticatedDocumentosIdRoute
  AuthenticatedMatriculasBecasPosgradoRoute: typeof AuthenticatedMatriculasBecasPosgradoRoute
  AuthenticatedMatriculasCoberturaPicRoute: typeof AuthenticatedMatriculasCoberturaPicRoute
  AuthenticatedMatriculasCohortesRoute: typeof AuthenticatedMatriculasCohortesRoute
  AuthenticatedMatriculasResumenRoute: typeof AuthenticatedMatriculasResumenRoute
  AuthenticatedMatriculasTransferenciasRoute: typeof AuthenticatedMatriculasTransferenciasRoute
  AuthenticatedModificacionesIdRoute: typeof AuthenticatedModificacionesIdRoute
  AuthenticatedProyectosIdRoute: typeof AuthenticatedProyectosIdRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedDashboardIndexRoute: typeof AuthenticatedDashboardIndexRoute
  AuthenticatedDocumentosIndexRoute: typeof AuthenticatedDocumentosIndexRoute
  AuthenticatedMatriculasIndexRoute: typeof AuthenticatedMatriculasIndexRoute
  AuthenticatedModificacionesIndexRoute: typeof AuthenticatedModificacionesIndexRoute
  AuthenticatedProyectosIndexRoute: typeof AuthenticatedProyectosIndexRoute
  AuthenticatedAdminRolesIdRoute: typeof AuthenticatedAdminRolesIdRoute
  AuthenticatedAdminUsuariosIdRoute: typeof AuthenticatedAdminUsuariosIdRoute
  AuthenticatedAdminAuditoriaIndexRoute: typeof AuthenticatedAdminAuditoriaIndexRoute
  AuthenticatedAdminRolesIndexRoute: typeof AuthenticatedAdminRolesIndexRoute
  AuthenticatedAdminUsuariosIndexRoute: typeof AuthenticatedAdminUsuariosIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAgendaRoute: AuthenticatedAgendaRouteWithChildren,
  AuthenticatedBalanceRoute: AuthenticatedBalanceRouteWithChildren,
  AuthenticatedCatalogosRoute: AuthenticatedCatalogosRouteWithChildren,
  AuthenticatedEjecucionRoute: AuthenticatedEjecucionRouteWithChildren,
  AuthenticatedIntegracionRoute: AuthenticatedIntegracionRouteWithChildren,
  AuthenticatedNominaRoute: AuthenticatedNominaRouteWithChildren,
  AuthenticatedNormatividadRoute: AuthenticatedNormatividadRouteWithChildren,
  AuthenticatedPerfilRoute: AuthenticatedPerfilRouteWithChildren,
  AuthenticatedPresupuestoRoute: AuthenticatedPresupuestoRouteWithChildren,
  AuthenticatedSarViaticosRoute: AuthenticatedSarViaticosRouteWithChildren,
  AuthenticatedAdminVigenciasRoute: AuthenticatedAdminVigenciasRoute,
  AuthenticatedDashboardInformesRoute: AuthenticatedDashboardInformesRoute,
  AuthenticatedDashboardSeguimientoRoute:
    AuthenticatedDashboardSeguimientoRoute,
  AuthenticatedDocumentosIdRoute: AuthenticatedDocumentosIdRoute,
  AuthenticatedMatriculasBecasPosgradoRoute:
    AuthenticatedMatriculasBecasPosgradoRoute,
  AuthenticatedMatriculasCoberturaPicRoute:
    AuthenticatedMatriculasCoberturaPicRoute,
  AuthenticatedMatriculasCohortesRoute: AuthenticatedMatriculasCohortesRoute,
  AuthenticatedMatriculasResumenRoute: AuthenticatedMatriculasResumenRoute,
  AuthenticatedMatriculasTransferenciasRoute:
    AuthenticatedMatriculasTransferenciasRoute,
  AuthenticatedModificacionesIdRoute: AuthenticatedModificacionesIdRoute,
  AuthenticatedProyectosIdRoute: AuthenticatedProyectosIdRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  AuthenticatedDashboardIndexRoute: AuthenticatedDashboardIndexRoute,
  AuthenticatedDocumentosIndexRoute: AuthenticatedDocumentosIndexRoute,
  AuthenticatedMatriculasIndexRoute: AuthenticatedMatriculasIndexRoute,
  AuthenticatedModificacionesIndexRoute: AuthenticatedModificacionesIndexRoute,
  AuthenticatedProyectosIndexRoute: AuthenticatedProyectosIndexRoute,
  AuthenticatedAdminRolesIdRoute: AuthenticatedAdminRolesIdRoute,
  AuthenticatedAdminUsuariosIdRoute: AuthenticatedAdminUsuariosIdRoute,
  AuthenticatedAdminAuditoriaIndexRoute: AuthenticatedAdminAuditoriaIndexRoute,
  AuthenticatedAdminRolesIndexRoute: AuthenticatedAdminRolesIndexRoute,
  AuthenticatedAdminUsuariosIndexRoute: AuthenticatedAdminUsuariosIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
